### ISSUE TITLE
Convertions Breaks up.

### ISSUE THREAD

**Issue by PittStone** [C0untFloyd/roop-unleashed#10]
**Describe the bug**
The App Crash sometimes after click on save video to a path.
Than after new start with: 
python run.py --execution-provider cuda --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9

The Convertion stops with a Error after making frames from the video:

if compute_cosine_distance(target_embedding, dest_embedding) <= DIST_THRESHOLD:
TypeError: 'staticmethod' object is not callable

**To Reproduce**
1. select image, select target video
2. Click on 'start'
3. save the videoname
4. after frame extraction i see the error

**Details**
What OS are you using?

- [ ] Windows 

Are you try to use a GPU?

- [ ] NVIDIA

**Screenshots**

**Sanity Check**
- [ ] I have followed the installation guide

After i delete the whole folder and install it again to a new folder, it works again. Than after few convertion it crash and the Error appears after i restart the App with CMD Window:
python run.py --execution-provider cuda --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9

**Comment by C0untFloyd** [comment]
I don't have a clue. Is face-swapping on images working? Perhaps your harddisk is faulty? Can you try converting a video using the `many faces` option?

**Comment by Kambeiz** [comment]
Same error as well on a Kubuntu 22.04. Using the `many faces` options solves the problem though. In my case the problem seems to come from TKinter : 

`[ROOP.CORE] Creating temp resources...
[ROOP.CORE] Extracting frames...
[ROOP.CORE] ROOP.FACE-SWAPPER in progress...
Processing:  76%|███████████████████████████████████████████████████████████████████████▍                      | 19/25 [00:02<00:00,  9.16frame/s, memory_usage=01.84GB, execution_providers=['CUDAExecutionProvider'], execution_threads=8]
Exception in Tkinter callback

Traceback (most recent call last):
  File "/home/doubn/anaconda3/envs/deepfake/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/doubn/anaconda3/envs/deepfake/lib/python3.9/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/doubn/Bureau/AI_tools/Deepfake_test/roop-unleashed-main/roop/ui.py", line 102, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', command=lambda: select_output_path(start))
  File "/home/doubn/Bureau/AI_tools/Deepfake_test/roop-unleashed-main/roop/ui.py", line 265, in select_output_path
    start()
  File "/home/doubn/Bureau/AI_tools/Deepfake_test/roop-unleashed-main/roop/core.py", line 199, in start
    frame_processor.process_video(roop.globals.SELECTED_FACE_DATA_INPUT, roop.globals.SELECTED_FACE_DATA_OUTPUT, temp_frame_paths)
  File "/home/doubn/Bureau/AI_tools/Deepfake_test/roop-unleashed-main/roop/processors/frame/face_swapper.py", line 117, in process_video
    roop.processors.frame.core.process_video(source_face, target_face, temp_frame_paths, process_frames)
  File "/home/doubn/Bureau/AI_tools/Deepfake_test/roop-unleashed-main/roop/processors/frame/core.py", line 88, in process_video
    multi_process_frame(False, source_face, target_face, frame_paths, process_frames, lambda: update_progress(progress))
  File "/home/doubn/Bureau/AI_tools/Deepfake_test/roop-unleashed-main/roop/processors/frame/core.py", line 60, in multi_process_frame
    future.result()
  File "/home/doubnn/anaconda3/envs/deepfake/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/doubn/anaconda3/envs/deepfake/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/doubn/anaconda3/envs/deepfake/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/doubn/Bureau/AI_tools/Deepfake_test/roop-unleashed-main/roop/processors/frame/face_swapper.py", line 93, in process_frames
    result = process_frame(source_face, target_face, temp_frame)
  File "/home/doubn/Bureau/AI_tools/Deepfake_test/roop-unleashed-main/roop/processors/frame/face_swapper.py", line 75, in process_frame
    if compute_cosine_distance(target_embedding, dest_embedding) <= DIST_THRESHOLD:
TypeError: 'staticmethod' object is not callable
`

**Comment by C0untFloyd** [comment]
I removed the staticmethod attribute in the latest version. Please try again and let me know if it's working for you.

**Comment by PittStone** [comment]
It works now for me. Thanks.

**Comment by PittStone** [comment]
Another Problem with Converting Error is with Batch encoding on v2.0.3 
It converts the first video in the folder and than brakes up because it says there is already a temp.mp4 in the folder. so the app doesnt name the produced .mp4 correctly.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\buzzc\roop_unleashed_win\installer_files\env\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\buzzc\roop_unleashed_win\installer_files\env\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\buzzc\roop_unleashed_win\roop-unleashed\roop\ui.py", line 104, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', command=lambda: select_output_path(start))
  File "C:\Users\buzzc\roop_unleashed_win\roop-unleashed\roop\ui.py", line 270, in select_output_path
    start()
  File "C:\Users\buzzc\roop_unleashed_win\roop-unleashed\roop\core.py", line 161, in start
    batch_process()
  File "C:\Users\buzzc\roop_unleashed_win\roop-unleashed\roop\core.py", line 278, in batch_process
    move_temp(video, roop.globals.output_path)
  File "C:\Users\buzzc\roop_unleashed_win\roop-unleashed\roop\utilities.py", line 107, in move_temp
    shutil.move(temp_output_path, output_path)
  File "C:\Users\buzzc\roop_unleashed_win\installer_files\env\lib\shutil.py", line 814, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'G:/Downloads/swap3/Neuer Ordner\temp.mp4' already exists
