### ISSUE TITLE
Will not Launch

### ISSUE THREAD

**Issue by Moonist59** [C0untFloyd/roop-unleashed#101]
HI,
Windows 11

Launching App
Traceback (most recent call last):
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 976, in send
    self.connect()
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\roop-unleashed\roop\core.py", line 340, in run
    if not pre_check():
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\roop-unleashed\roop\core.py", line 153, in pre_check
    util.conditional_download(download_directory_path, ['https://huggingface.co/countfloyd/deepfake/resolve/main/rd64-uni-refined.pth'])
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\roop-unleashed\roop\utilities.py", line 176, in conditional_download
    request = urllib.request.urlopen(url) # type: ignore[attr-defined]
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\X\roop-unleashed\installer\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

Done!
Press any key to continue . . .

**Comment by C0untFloyd** [comment]
Internet problems on your side?
You could download the models manually (put them into the models folder):
https://huggingface.co/CountFloyd/deepfake/tree/main

**Comment by Moonist59** [comment]
Hi,
1.  Thank you for your hard work.  This is a cool project.
2. I reinstalled the program.
3. I downloaded the 3 files from hugging.
4. I put them in the models directory. D:\X\roop-unleashed\roop-unleashed\models

Launching App
Traceback (most recent call last):
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\X\roop-unleashed\installer_files\env\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\X\roop-unleashed\installer_files\env\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\X\roop-unleashed\installer_files\env\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\X\roop-unleashed\installer_files\env\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "D:\X\roop-unleashed\installer_files\env\lib\http\client.py", line 976, in send
    self.connect()
  File "D:\X\roop-unleashed\installer_files\env\lib\http\client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\X\roop-unleashed\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\X\roop-unleashed\installer_files\env\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\X\roop-unleashed\installer_files\env\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\X\roop-unleashed\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "D:\X\roop-unleashed\roop-unleashed\roop\core.py", line 340, in run
    if not pre_check():
  File "D:\X\roop-unleashed\roop-unleashed\roop\core.py", line 153, in pre_check
    util.conditional_download(download_directory_path, ['https://huggingface.co/countfloyd/deepfake/resolve/main/rd64-uni-refined.pth'])
  File "D:\X\roop-unleashed\roop-unleashed\roop\utilities.py", line 176, in conditional_download
    request = urllib.request.urlopen(url) # type: ignore[attr-defined]
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\X\roop-unleashed\installer_files\env\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

Done!
Press any key to continue . . .

Any suggestions

**Comment by C0untFloyd** [comment]
Oh sorry, the clip model above needs to be in the clip subfolder. Here's a screenshot. Hopefully you can download the others, it'sa lot!
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/5958875c-c77a-4c52-bb7b-8d729f29b851)

**Comment by Moonist59** [comment]
Excellent!  All working as should.  Thanks for the help!

**Comment by MasterInkanMayan** [comment]
I am getting the same error as you and i downloaded the files from hugging face but i am not able to differentiate between clip and CodeFormer based on the file names (sorry, i am a noob in all this), could you please share which files to put where. 
I have attached an image with all the files that were available and I downloaded from hugging face. 

![GitHub](https://github.com/C0untFloyd/roop-unleashed/assets/161099653/b984f8fe-075d-4c2a-8ee5-270a298ade82)
 
Your help will be highly appreciated, thank you!

**Comment by C0untFloyd** [comment]
rd64-uni-refined.pth goes into CLIP
CodeFormerv0.1.onnx into CodeFormer

models folder looks like this
![models folder](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/0990f015-650a-4cd9-8034-422926a5fc00)

**Comment by MasterInkanMayan** [comment]
Thank you so much, it works flawlessly!!
