### ISSUE TITLE
Command line processing with -s -t -o options fails with "AttributeError: 'list' object has no attribute 'embedding'"

### ISSUE THREAD

**Issue by by321** [C0untFloyd/roop-unleashed#114]
Running from command line using the -s -t -o options doesn't work, however using the GUI to select the same source and target images works just fine.

For example:

```
C:\test\roopunleashed>python run.py -s d:\a.png -t d:\b.png -o d:\output.png
Loading roop.processors.frame.face_swapper
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\test1/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\test1/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\test1/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\test1/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\test1/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
[ROOP.CORE] ROOP.FACE-SWAPPER in progress...
Traceback (most recent call last):
  File "C:\test\roopunleashed\run.py", line 6, in <module>
    core.run()
  File "C:\test\roopunleashed\roop\core.py", line 308, in run
    start()
  File "C:\test\roopunleashed\roop\core.py", line 181, in start
    frame_processor.process_image(roop.globals.SELECTED_FACE_DATA_INPUT, roop.globals.SELECTED_FACE_DATA_OUTPUT, target, roop.globals.output_path)
  File "C:\test\roopunleashed\roop\processors\frame\face_swapper.py", line 109, in process_image
    result = process_frame(source_face, target_face, target_frame)
  File "C:\test\roopunleashed\roop\processors\frame\face_swapper.py", line 70, in process_frame
    target_embedding = target_face.embedding
AttributeError: 'list' object has no attribute 'embedding'
```
However in GUI (started by 'python run.py'), by selecting a.png as the source image and b.png as target image, I could generate output.png without any problem.

**Comment by C0untFloyd** [comment]
There's nothing you can't do with the UI, the CLI was very much neglected by me.
