### ISSUE TITLE
FileNotFoundError: [winError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by kkushsaini** [C0untFloyd/roop-unleashed#119]
I'm using Win11 and after following all the steps mentioned @ https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/1-Click-DeepFake-Tutorial.md

everything goes well but when in the UI i hit the start button, i get this error in cmd:

Traceback (most recent call last):
  File "D:\stable diffusion\roop-unleashed\venv\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable diffusion\roop-unleashed\venv\Lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable diffusion\roop-unleashed\venv\Lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable diffusion\roop-unleashed\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable diffusion\roop-unleashed\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\stable diffusion\roop-unleashed\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable diffusion\roop-unleashed\venv\Lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\stable diffusion\roop-unleashed\roop\ui.py", line 606, in start_swap
    batch_process([file.name for file in target_files], use_clip, clip_text)
  File "D:\stable diffusion\roop-unleashed\roop\core.py", line 301, in batch_process
    fps = util.detect_fps(v)
          ^^^^^^^^^^^^^^^^^^
  File "D:\stable diffusion\roop-unleashed\roop\utilities.py", line 43, in detect_fps
    output = subprocess.check_output(command).decode().strip().split('/')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified.

Help me guys..

**Comment by phineas-pta** [comment]
try run `ffprobe -version`

if error then u need setup ffmpeg properly (ffprobe comes together with ffmpeg)

**Comment by acSpock** [comment]
I'm getting the same error. @kkushsaini any luck?
