### ISSUE TITLE
[Silicon Mac] Select CoreML in Settings but CUDA / CPU is used instead 

### ISSUE THREAD

**Issue by sftpct** [C0untFloyd/roop-unleashed#138]
**Describe the bug**

Selecting CoreML in settings (and restarting) does not actually persist into the settings. Instead, the algorithm falls back to trying to use CUDA, then fails because I am on a Mac, and then uses CPU instead. I surmise this from the terminal output.

**To Reproduce**
I am on Ventura of a M1 Macbook Pro, so apple silicon instead of legacy intel. I run `python run.py`, go to settings, select CoreML, click restart server, and then try to generate a video. In the terminal output, I see

```
Traceback (most recent call last):
  File "/Users/user/sandbox/roop-unleashed/chain_img_processor/image.py", line 127, in init_processor
    self.add_processor_to_list(processor_id)
  File "/Users/user/sandbox/roop-unleashed/chain_img_processor/image.py", line 113, in add_processor_to_list
    obj.init_plugin()
  File "/Users/user/sandbox/roop-unleashed/plugins/plugin_dmdnet.py", line 72, in init_plugin
    create(self.device)
  File "/Users/user/sandbox/roop-unleashed/plugins/plugin_dmdnet.py", line 179, in create
    weights = torch.load('./models/DMDNet.pth')
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

It shouldn't be attempting to use CUDA because I am clearly passing in CoreML, as evident by the custom logs I added below.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
2.7.7

**Screenshots**

Some useful debug logs of a run. I even added some print statements myself.

```
trying to
process onnx file: /Users/user/.insightface/models/buffalo_l/1k3d68.onnx
getting model wit hargs  {'providers': ['CoreMLExecutionProvider']}
providers:  ['CoreMLExecutionProvider']
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
got model  <insightface.model_zoo.landmark.Landmark object at 0x1760d7490>
find model: /Users/user/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
process onnx file: /Users/user/.insightface/models/buffalo_l/2d106det.onnx
getting model wit hargs  {'providers': ['CoreMLExecutionProvider']}
providers:  ['CoreMLExecutionProvider']
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
got model  <insightface.model_zoo.landmark.Landmark object at 0x176267700>
find model: /Users/user/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
process onnx file: /Users/user/.insightface/models/buffalo_l/det_10g.onnx
getting model wit hargs  {'providers': ['CoreMLExecutionProvider']}
providers:  ['CoreMLExecutionProvider']
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
got model  <insightface.model_zoo.retinaface.RetinaFace object at 0x1772b8580>
find model: /Users/user/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
process onnx file: /Users/user/.insightface/models/buffalo_l/genderage.onnx
getting model wit hargs  {'providers': ['CoreMLExecutionProvider']}
providers:  ['CoreMLExecutionProvider']
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
got model  <insightface.model_zoo.attribute.Attribute object at 0x1772b85e0>
find model: /Users/user/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
process onnx file: /Users/user/.insightface/models/buffalo_l/w600k_r50.onnx
getting model wit hargs  {'providers': ['CoreMLExecutionProvider']}
providers:  ['CoreMLExecutionProvider']
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
use provided session
got model  <insightface.model_zoo.arcface_onnx.ArcFaceONNX object at 0x1772b8700>
find model: /Users/user/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
using GPU providers:  ['CoreMLExecutionProvider']
set det-size: (640, 640)
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "/Users/user/sandbox/roop-unleashed/chain_img_processor/image.py", line 127, in init_processor
    self.add_processor_to_list(processor_id)
  File "/Users/user/sandbox/roop-unleashed/chain_img_processor/image.py", line 113, in add_processor_to_list
    obj.init_plugin()
  File "/Users/user/sandbox/roop-unleashed/plugins/plugin_dmdnet.py", line 72, in init_plugin
    create(self.device)
  File "/Users/user/sandbox/roop-unleashed/plugins/plugin_dmdnet.py", line 179, in create
    weights = torch.load('./models/DMDNet.pth')
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Users/user/sandbox/roop-unleashed/venv/lib/python3.9/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
providers:  ['CoreMLExecutionProvider']
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]

```

**Comment by C0untFloyd** [comment]
You need to restart the whole app currently as all the models need to be reloaded.
