### ISSUE TITLE
raise HTTPError

### ISSUE THREAD

**Issue by lapwrr** [C0untFloyd/roop-unleashed#168]
Launching App
Loading roop.processors.frame.face_swapper
Loading roop.processors.frame.face_enhancer
Traceback (most recent call last):
  File "C:\Users\86135\installer\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "C:\Users\86135\installer\roop-unleashed\roop\core.py", line 304, in run
    if not frame_processor.pre_check():
  File "C:\Users\86135\installer\roop-unleashed\roop\processors\frame\face_swapper.py", line 32, in pre_check
    conditional_download(download_directory_path, ['https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx'])
  File "C:\Users\86135\installer\roop-unleashed\roop\utilities.py", line 146, in conditional_download
    request = urllib.request.urlopen(url) # type: ignore[attr-defined]
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

Done!

**Details**
What OS are you using?
 Windows 

Are you using a GPU?
NVIDIA

**Comment by phineas-pta** [comment]
update roop unleashed

**Comment by lapwrr** [comment]
> 更新roop释放
update
Traceback (most recent call last):
  File "C:\Users\86135\installer\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "C:\Users\86135\installer\roop-unleashed\roop\core.py", line 304, in run
    if not frame_processor.pre_check():
  File "C:\Users\86135\installer\roop-unleashed\roop\processors\frame\face_swapper.py", line 32, in pre_check
    conditional_download(download_directory_path, ['https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx'])
  File "C:\Users\86135\installer\roop-unleashed\roop\utilities.py", line 146, in conditional_download
    request = urllib.request.urlopen(url) # type: ignore[attr-defined]
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\86135\installer\installer_files\env\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054]
