### ISSUE TITLE
Text Masking Error

### ISSUE THREAD

**Issue by hellfirej** [C0untFloyd/roop-unleashed#177]
**Describe the bug**
When I try adding words into the masking text I get the following error in Roop "Error txt2clip" when doing the masking preview

Terminal says this:
roop-unleashed/chain_img_processor/image.py", line 86, in run_chain
img = self.processors_objects[proc_id][thread_index].process(img,params)
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'txt2clip'

**To Reproduce**
Steps to reproduce the behavior:
1. In Roop check "use Text Masking"
2. Click on "show Mask Preview
4. See error "txt2clip"


What OS are you using?
 Mac

Are you using a GPU?
Mac

**Which version of roop unleashed are you using?**
2.7.9

**Comment by C0untFloyd** [comment]
In your other post in discussions the error text was a bit longer, they key error is important. It means the plugin couldn't be loaded. Without the reason for this and the rest of the error msg I can only guess what is going wrong:
Perhaps you're missing the clip2seg models or they are corrupt? There should be this folder/file in your installation:
"models\CLIP\rd64-uni-refined.pth"
Could you try running it on CPU only?

**Comment by hellfirej** [comment]
Thank you for the response! I'm unfortunately super new to all of the tech side of things :(
Is there a way for me to reinstall that particular module? 
Unfortunately only a Mac here for me to test on - If there's any info I can get that would help please let me know! I really appreciate the help!
:)

**Comment by C0untFloyd** [comment]
No problem, could you dump the whole terminal output here from starting the app to running text2mask?

**Comment by hellfirej** [comment]
Okay so this is everything after start up

find model: /Users/mymac/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/mymac/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/mymac/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/mymac/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/mymac/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
JAA PLUGIN ERROR: plugin_txt2clip error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/roop-unleashed/jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "/Users/mymac/roop-unleashed/plugins/plugin_txt2clip.py", line 7, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'
JAA PLUGIN ERROR: plugin_dmdnet error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/roop-unleashed/jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "/Users/mymac/roop-unleashed/plugins/plugin_dmdnet.py", line 11, in <module>
    from torchvision.ops import roi_align
ModuleNotFoundError: No module named 'torchvision'
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'dmdnet'
Error init processor plugin codeformer... red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/Users/mymac/roop-unleashed/plugins/plugin_codeformer.py", line 39, in init_plugin
    import plugins.codeformer_app_cv2
  File "/Users/mymac/roop-unleashed/plugins/codeformer_app_cv2.py", line 15, in <module>
    from codeformer.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'codeformer'
JAA PLUGIN ERROR: plugin_txt2clip error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/roop-unleashed/jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "/Users/mymac/roop-unleashed/plugins/plugin_txt2clip.py", line 7, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'
JAA PLUGIN ERROR: plugin_dmdnet error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/roop-unleashed/jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "/Users/mymac/roop-unleashed/plugins/plugin_dmdnet.py", line 11, in <module>
    from torchvision.ops import roi_align
ModuleNotFoundError: No module named 'torchvision'
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'dmdnet'
Error init processor plugin codeformer... red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/Users/jamemac/roop-unleashed/plugins/plugin_codeformer.py", line 39, in init_plugin
    import plugins.codeformer_app_cv2
  File "/Users/mymac/roop-unleashed/plugins/codeformer_app_cv2.py", line 15, in <module>
    from codeformer.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'codeformer'
JAA PLUGIN ERROR: plugin_txt2clip error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/roop-unleashed/jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "/Users/mymac/roop-unleashed/plugins/plugin_txt2clip.py", line 7, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'
JAA PLUGIN ERROR: plugin_dmdnet error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/roop-unleashed/jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "/Users/mymac/roop-unleashed/plugins/plugin_dmdnet.py", line 11, in <module>
    from torchvision.ops import roi_align
ModuleNotFoundError: No module named 'torchvision'
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'dmdnet'
Error init processor plugin codeformer... red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/Users/mymac/roop-unleashed/plugins/plugin_codeformer.py", line 39, in init_plugin
    import plugins.codeformer_app_cv2
  File "/Users/mymac/roop-unleashed/plugins/codeformer_app_cv2.py", line 15, in <module>
    from codeformer.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'codeformer'
Error init processor plugin txt2clip... red
Traceback (most recent call last):
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'txt2clip'
Traceback (most recent call last):
  File "/Usersmymac/venv/lib/python3.11/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/mymac/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/venv/lib/python3.11/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/roop-unleashed/roop/ui.py", line 572, in on_preview_mask
    current_frame = preview_mask(current_frame, clip_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/roop-unleashed/roop/core.py", line 264, in preview_mask
    temp_frame, _ = roop.globals.IMAGE_CHAIN_PROCESSOR.run_chain(maskimage,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/roop-unleashed/chain_img_processor/image.py", line 88, in run_chain
    img = self.processors_objects[proc_id][thread_index].process(img,params)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'txt2clip'

**Comment by C0untFloyd** [comment]
`JAA PLUGIN ERROR: plugin_txt2clip error on load: No module named 'torchvision' red
Traceback (most recent call last):` that's the problem. This also fails for the dmdnet enhancer.
At least the Torch/Torchvision module isn't installed.
You could try running `pip install -r requirements.txt` again to try to re-install everything or just torchvision `pip install torchvision==0.15.2`

**Comment by hellfirej** [comment]
Im no longer getting the original error but now this one 

JAA PLUGIN ERROR: plugin_txt2clip error on load: No module named 'ftfy' red

Sorry to be a pain, I tired both the re install and the other but no luck as yet

Thanks so much for your help its very much appreciated!

**Comment by C0untFloyd** [comment]
But that means you're hopefully only missing the last 2 modules...
You could try installing them until you have no more error, although it's weird that it doesn't seem to get installled with the requirements.
For this just do `pip install ftfy`
