### ISSUE TITLE
KeyError: 'dmdnet'

### ISSUE THREAD

**Issue by navasgejza** [C0untFloyd/roop-unleashed#190]
I have installed this program to my own Windows 10 system computer with the help of the turtorial video https://www.youtube.com/watch?v=EZ9k388EnX8
I have Processor Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz, 3696 Mhz, 4 Core(s), 8 Logical Processor(s)
My GPU is Radeon RX 5500 XT withthe latest updates
Afeter I have installed every elements, I tried it, but it doesn't work. 
In the anaconda prompt I get this error message: KeyError: 'dmdnet'
It only starts processing with GFPGAN enhancer. Codeformer and DMDNET doesn't start processing.
Here's the complete line of the faulty process. Hope you can help me about it. Bests, Géza.

Launching App
Using provider [] - Device:cpu
Running on local URL:  http:/..........................
To create a public link, set `share=True` in `launch()`.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Geza/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Geza/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Geza/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Geza/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Geza/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
JAA PLUGIN ERROR: plugin_dmdnet error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\plugin_dmdnet.py", line 11, in <module>
    from torchvision.ops import roi_align
ModuleNotFoundError: No module named 'torchvision'
JAA PLUGIN ERROR: plugin_txt2clip error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\plugin_txt2clip.py", line 7, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
KeyError: 'dmdnet'
Error init processor plugin codeformer... red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\plugin_codeformer.py", line 39, in init_plugin
    import plugins.codeformer_app_cv2
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\codeformer_app_cv2.py", line 15, in <module>
    from codeformer.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'codeformer'
JAA PLUGIN ERROR: plugin_dmdnet error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\plugin_dmdnet.py", line 11, in <module>
    from torchvision.ops import roi_align
ModuleNotFoundError: No module named 'torchvision'
JAA PLUGIN ERROR: plugin_txt2clip error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\plugin_txt2clip.py", line 7, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
KeyError: 'dmdnet'
Error init processor plugin codeformer... red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\plugin_codeformer.py", line 39, in init_plugin
    import plugins.codeformer_app_cv2
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\codeformer_app_cv2.py", line 15, in <module>
    from codeformer.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'codeformer'
JAA PLUGIN ERROR: plugin_dmdnet error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\plugin_dmdnet.py", line 11, in <module>
    from torchvision.ops import roi_align
ModuleNotFoundError: No module named 'torchvision'
JAA PLUGIN ERROR: plugin_txt2clip error on load: No module named 'torchvision' red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 97, in init_plugin
    mod = self.import_plugin("plugins."+modname)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\jaa.py", line 178, in import_plugin
    __import__(module_name)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\plugin_txt2clip.py", line 7, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
KeyError: 'dmdnet'
Error init processor plugin codeformer... red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\plugin_codeformer.py", line 39, in init_plugin
    import plugins.codeformer_app_cv2
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\plugins\codeformer_app_cv2.py", line 15, in <module>
    from codeformer.facelib.detection import init_detection_model
ModuleNotFoundError: No module named 'codeformer'
Creating DSC 5584 ok__temp.mp4 with 30.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '1920x1080', '-pix_fmt', 'bgr24', '-r', '30.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', 'C:\\Users\\Geza\\downloads\\roop\\installer\\roop-unleashed\\output\\DSC 5584 ok__temp.mp4']
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
KeyError: 'dmdnet'
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
KeyError: 'dmdnet'
Error init processor plugin dmdnet... red
Traceback (most recent call last):
Error init processor plugin dmdnet... red
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 129, in init_processor    self.add_processor_to_list(processor_id)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
KeyError: 'dmdnet'
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 114, in add_processor_to_list
    obj = self.processors[processor_id](self)
KeyError: 'dmdnet'
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Traceback (most recent call last):
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\roop\ui.py", line 643, in start_swap
    batch_process([file.name for file in target_files], use_clip, clip_text, processing_method == "In-Memory")
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\roop\core.py", line 359, in batch_process
    roop.globals.VIDEO_CHAIN_PROCESSOR.run_batch_chain(v, videofinalnames[index], fps,
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\video.py", line 163, in run_batch_chain
    future.result()
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\concurrent\futures\_base.py", line 451, in result    return self.__get_result()
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Geza\downloads\roop\installer\installer_files\env\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\video.py", line 84, in process_frames
    resimg, _ = self.run_chain(frame, params, self.chain)
  File "C:\Users\Geza\downloads\roop\installer\roop-unleashed\chain_img_processor\image.py", line 88, in run_chain
    img = self.processors_objects[proc_id][thread_index].process(img,params)
KeyError: 'dmdnet'

**Comment by C0untFloyd** [comment]
You're missing torch/torchvision installation. The video isn't exactly great. That guy could have just changed the gpu-specific requirements to cpu and let the installer do it's work...
