### ISSUE TITLE
Protobuf parsing failed

### ISSUE THREAD

**Issue by linuxreitt** [C0untFloyd/roop-unleashed#191]
**Describe the bug**
Onnxruntime error

**To Reproduce**
When I first ran the webui, every model download ended with: urllib.error.ContentTooShortError: , it would exit to prompt and I'd have to run the run.py again, it would then begin to download the next model, I did this for all models:
RealESRGAN_x2plus.pth:  86%|▊| 55.1M/64.0M [00:17<00:02, 3
Traceback (most recent call last):

Finally I ran Load webui add photos and hit start but it fails.

**Details**
What OS are you using?
Linux

Are you using a GPU?
AMD GPU 
Intel 12th Gen Alder Lake CPU

**Which version of roop unleashed are you using?**
Latest

Error:
To create a public link, set `share=True` in `launch()`.
Forcing CPU for Face Analysis
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/linuxreitt/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/linuxreitt/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/linuxreitt/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/linuxreitt/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/linuxreitt/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Error init processor plugin dmdnet... red
Traceback (most recent call last):
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/plugin_dmdnet.py", line 71, in init_plugin
    create(self.device)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/plugin_dmdnet.py", line 179, in create
    weights = torch.load('./models/DMDNet.pth')
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Error init processor plugin gfpgan... red
Traceback (most recent call last):
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/plugin_gfpgan.py", line 44, in init_plugin
    model_gfpgan = onnxruntime.InferenceSession(model_path, None, providers=roop.globals.execution_providers)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/linuxreitt/Projects/Image-AI/roop-unleashed/models/GFPGANv1.4.onnx failed:Protobuf parsing failed.
Error init processor plugin codeformer... red
Traceback (most recent call last):
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/plugin_codeformer.py", line 39, in init_plugin
    import plugins.codeformer_app_cv2
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/codeformer_app_cv2.py", line 92, in <module>
    upsampler = set_realesrgan()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/codeformer_app_cv2.py", line 80, in set_realesrgan
    upsampler = RealESRGANer(
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/codeformer/basicsr/utils/realesrgan_utils.py", line 56, in __init__
    loadnet = torch.load(model_path, map_location=torch.device("cpu"))
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Error init processor plugin gfpgan... red
Traceback (most recent call last):
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/plugin_gfpgan.py", line 44, in init_plugin
    model_gfpgan = onnxruntime.InferenceSession(model_path, None, providers=roop.globals.execution_providers)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/linuxreitt/Projects/Image-AI/roop-unleashed/models/GFPGANv1.4.onnx failed:Protobuf parsing failed.
Error init processor plugin codeformer... red
Traceback (most recent call last):
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/plugin_codeformer.py", line 39, in init_plugin
    import plugins.codeformer_app_cv2
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/codeformer_app_cv2.py", line 92, in <module>
    upsampler = set_realesrgan()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/codeformer_app_cv2.py", line 80, in set_realesrgan
    upsampler = RealESRGANer(
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/codeformer/basicsr/utils/realesrgan_utils.py", line 56, in __init__
    loadnet = torch.load(model_path, map_location=torch.device("cpu"))
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Error init processor plugin gfpgan... red
Traceback (most recent call last):
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/plugin_gfpgan.py", line 44, in init_plugin
    model_gfpgan = onnxruntime.InferenceSession(model_path, None, providers=roop.globals.execution_providers)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/linuxreitt/Projects/Image-AI/roop-unleashed/models/GFPGANv1.4.onnx failed:Protobuf parsing failed.
Error init processor plugin codeformer... red
Traceback (most recent call last):
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 129, in init_processor
    self.add_processor_to_list(processor_id)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 115, in add_processor_to_list
    obj.init_plugin()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/plugin_codeformer.py", line 39, in init_plugin
    import plugins.codeformer_app_cv2
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/codeformer_app_cv2.py", line 92, in <module>
    upsampler = set_realesrgan()
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/codeformer_app_cv2.py", line 80, in set_realesrgan
    upsampler = RealESRGANer(
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/codeformer/basicsr/utils/realesrgan_utils.py", line 56, in __init__
    loadnet = torch.load(model_path, map_location=torch.device("cpu"))
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Processing image(s)
Traceback (most recent call last):
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/gradio/routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/gradio/utils.py", line 508, in async_iteration
    return await iterator.__anext__()
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/gradio/utils.py", line 501, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/gradio/utils.py", line 484, in run_sync_iterator_async
    return next(iterator)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/gradio/utils.py", line 853, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/gradio/utils.py", line 853, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/roop/ui.py", line 643, in start_swap
    batch_process([file.name for file in target_files], use_clip, clip_text, processing_method == "In-Memory")
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/roop/core.py", line 330, in batch_process
    roop.globals.BATCH_IMAGE_CHAIN_PROCESSOR.run_batch_chain(imagefiles, imagefinalnames, roop.globals.execution_threads, processors, params_gen_func)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/batchimage.py", line 89, in run_batch_chain
    future.result()
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/batchimage.py", line 66, in process_frames
    resimg, _ = self.run_chain(temp_frame, params, self.chain)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/chain_img_processor/image.py", line 88, in run_chain
    img = self.processors_objects[proc_id][thread_index].process(img,params)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/plugins/plugin_faceswap.py", line 56, in process
    frame = swap_face(params["input_face_datas"][face_index], face, frame)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/roop/face_util.py", line 98, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "/home/linuxreitt/Projects/Image-AI/roop-unleashed/roop/face_util.py", line 87, in get_face_swapper
    FACE_SWAPPER = insightface.model_zoo.get_model(model_path, providers=roop.globals.execution_providers)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/linuxreitt/anaconda3/envs/roopun/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/linuxreitt/Projects/Image-AI/roop-unleashed/models/inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by C0untFloyd** [comment]
The model weights are corrupt. Try downloading them manually:
https://huggingface.co/countfloyd/deepfake/resolve/main/inswapper_128.onnx
https://huggingface.co/countfloyd/deepfake/resolve/main/GFPGANv1.4.pth
https://huggingface.co/countfloyd/deepfake/resolve/main/GFPGANv1.4.onnx
https://github.com/csxmli2016/DMDNet/releases/download/v1/DMDNet.pth

This goes into models/clip:
https://huggingface.co/countfloyd/deepfake/resolve/main/rd64-uni-refined.pth

This into models/CodeFormer
https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth

models/CodeFormer/facelib:
https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/detection_Resnet50_Final.pth
https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/parsing_parsenet.pth

models/CodeFormer/realesrgan:
https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/RealESRGAN_x2plus.pth
