### ISSUE TITLE
No Face Detection

### ISSUE THREAD

**Issue by marlonio** [C0untFloyd/roop-unleashed#196]
An alert with NO FACE DETECTED appear and it's not possible to proceed with the faceswapping

**To Reproduce**
1. I made a clean install on Ubuntu
2. Every step of the installation has been completed
3. After starting the software (with CUDA as execution provider or without i get the same issue) i simply upload the picture

**Details**
What OS are you using?
- [X] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

I'm using Roop-Unleashed 2.8.2

![screenshot](https://github.com/C0untFloyd/roop-unleashed/assets/77846722/393013c8-5ea3-409e-9c25-3b3e5c1099dd)

**Comment by C0untFloyd** [comment]
That is actually one of my go-to test images, it should always work:
![grafik](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/9dcca6ce-cad9-4c9a-9f80-424d2d8eea59)

Can you dump the console output here? Perhaps you're missing the face recognition model.

**Comment by marlonio** [comment]
**This is the error in console:**

 ```
EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 803: system has unsupported display driver / cuda driver combination ; GPU=-1821708309 ; hostname=pcm-workstation ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=238 ; expr=cudaSetDevice(info_.device_id); 

 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Traceback (most recent call last):
  File "/home/pcm/Workplace/roop-unleashed/roop-env/lib/python3.11/site-packages/gradio/routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcm/Workplace/roop-unleashed/roop-env/lib/python3.11/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcm/Workplace/roop-unleashed/roop-env/lib/python3.11/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcm/Workplace/roop-unleashed/roop-env/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcm/Workplace/roop-unleashed/roop-env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/pcm/Workplace/roop-unleashed/roop-env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pcm/Workplace/roop-unleashed/roop-env/lib/python3.11/site-packages/gradio/utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/pcm/Workplace/roop-unleashed/roop/ui.py", line 415, in on_srcimg_changed
    raise gr.Error('No faces detected!')
gradio.exceptions.Error: 'No faces detected!'
```

I think about the face recognition model but i don't know where to find it (Is it supposed to be in the models folder? Whats the name? In case i don't find it where it's possible to download?)

**Comment by C0untFloyd** [comment]
It looks like you either don't have a cuda GPU or it's not installed correctly. Could you try changing the provider from cuda to cpu in the settings? Don't forget to apply settings and restart everything.

**Comment by marlonio** [comment]
With the CPU is working, that's strange cause i've installed the drivers for CUDA, maybe the problem could be the CUDNN, i will try to reinstall them and i'll let you know!
