### ISSUE TITLE
Error when using text masking

### ISSUE THREAD

**Issue by aaaAndreaG** [C0untFloyd/roop-unleashed#218]
Hi, i'm getting this issue when trying to use text masking: 
![3](https://github.com/C0untFloyd/roop-unleashed/assets/144906133/6c29a8e8-70bf-4c72-a89e-c906c0d2ce6f)
Didn't get this error on 2.7.9, however i can see the mask preview without problems, the issue is only present when clicking refresh or when processing a video. I'm using latest version 3.0.5 with rtx 4090 and threads set to 2 (tried changing the number of threads but nothing changed). Any ideas?
Traceback (most recent call last):
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "A:\roop-unleashed-main\roop\ui.py", line 581, in on_preview_frame_changed
    current_frame = live_swap(current_frame, roop.globals.face_swap_mode, use_clip, clip_text, SELECTED_INPUT_FACE_INDEX)
  File "A:\roop-unleashed-main\roop\core.py", line 230, in live_swap
    return process_mgr.process_frame(frame)
  File "A:\roop-unleashed-main\roop\ProcessMgr.py", line 276, in process_frame
    return self.process_face(self.options.selected_index, face, temp_frame)
  File "A:\roop-unleashed-main\roop\ProcessMgr.py", line 318, in process_face
    img_mask = p.Run(orig_frame, self.options.masking_text)
  File "A:\roop-unleashed-main\roop\processors\Mask_Clip2Seg.py", line 40, in Run
    source_image_small = cv2.resize(img1, (256,256))
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by muemar79** [comment]
Got the same error. Using latest version. Also have a lot of trouble, that the text masking does often not recognize the text samples. I always got a black screen on the preview image. If it recognize a mask description like lips, mouth or something, I got the error above or it hangs sometimes while in progress.

**Comment by papagodzilla** [comment]
The same thing happens sometimes it works Sometimes it shows the above error.

**Comment by C0untFloyd** [comment]
Never had this error, tried everything to make this happen. I added some extra safety boundary checks, perhaps this is the problem 🤷‍♂️ 
> Also have a lot of trouble, that the text masking does often not recognize the text samples.
Nothing changed in this area but the recognition has problems with very tiny things like e.g. lips or fingers and also the face resolution matters. Be creative with your words for example I found "chin" working better than "mouth" sometimes.

**Comment by muemar79** [comment]
I will test it with different words. The error occurs in my oppinion with one of the latest updates. Before, I could create a lot of videos using masking without any problems. Current I am using an old GTX 1070TI with 8GB, tomorrow my new rtx4070 will arrive. At least it has 12 GB. But I don´t think, it has something to do with the GPU, but who knows. we will see.

**Comment by C0untFloyd** [comment]
Updated to latest version with the mentioned safety measures?

**Comment by muemar79** [comment]
Yes I am on 3.0.6 with the very last update. I check for updates minimum once per day.

**Comment by aaaAndreaG** [comment]
Seems to be fixed now. Using the new 3.0.7 version. Thanks

**Comment by muemar79** [comment]
just updated, will test it so. Thanks
