### ISSUE TITLE
Codeformer with Macos MPS not working (Sonoma 14.0)

### ISSUE THREAD

**Issue by aqgasa** [C0untFloyd/roop-unleashed#269]
I'm running roop-unleashed on a Mac M2, Sonoma 14.0.

This is the output when I try to use MPS and codeformer:

Sorting videos/images
Applied providers: ['CoreMLExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CoreMLExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Traceback (most recent call last):
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/utils.py", line 503, in async_iteration
    return await iterator.__anext__()
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/user/roop-unleashed/roop/ui.py", line 713, in start_swap
    batch_process(list_files_process, use_clip, clip_text, processing_method == "In-Memory processing", progress)
  File "/Users/user/roop-unleashed/roop/core.py", line 242, in batch_process
    process_mgr.initialize(roop.globals.INPUT_FACES, roop.globals.TARGET_FACES, options)
  File "/Users/user/roop-unleashed/roop/ProcessMgr.py", line 86, in initialize
    p.Initialize(devicename)
  File "/Users/user/roop-unleashed/roop/processors/Enhance_CodeFormer.py", line 33, in Initialize
    self.io_binding.bind_output(model_outputs[0].name, self.devicename)
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 519, in bind_output
    get_ort_device_type(device_type, device_id),
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 21, in get_ort_device_type
    raise Exception("Unsupported device type: " + device_type)
Exception: Unsupported device type: mps
Traceback (most recent call last):
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1303, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/Users/user/roop-unleashed/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1278, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_resultfiles_finished) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [image, video]
Received outputs:
    [None]

**Comment by C0untFloyd** [comment]
Does it work with GFPGAN? I don't have a Mac but I've seen in other forks that they disabled CoreML Support for all ONNX Enhancers...

**Comment by C0untFloyd** [comment]
But it does when switching to CPU? What about the face swapping without enhancers? Does that work with CoreML?

**Comment by phineas-pta** [comment]
@C0untFloyd it's a deeper problem with onnxruntime

`self.io_binding.bind_output` can accept device `cuda` but for mac there's none

so i think it's best to bind to cpu

**Comment by C0untFloyd** [comment]
Ah ok, thanks for clearing this up. I was searching the internet for this but couldn't find anything, was wondering why face swapping even works when this is onnxruntime too. I guess I would just need to test if it's a cuda device and if not always set it to cpu. This should be a fast hotfix.

**Comment by C0untFloyd** [comment]
Could you try with v3.2.0 now? It should fallback to cpu now.

**Comment by phineas-pta** [comment]
@aqgasa u need check

i dont have mac to verify
