### ISSUE TITLE
Livecam in new version 3.2 not working anymore

### ISSUE THREAD

**Issue by C0untFloyd** [C0untFloyd/roop-unleashed#278]
### Discussed in https://github.com/C0untFloyd/roop-unleashed/discussions/277

<div type='discussions-op-text'>

<sup>Originally posted by **aroca69** October  8, 2023</sup>
With the new version the livecam is not working anymore, could you cheek?
Many thanks,</div>

**Comment by C0untFloyd** [comment]
Tbh, I didn't test the livecam after refactoring a lot of stuff. Will take a look into it tomorrow.

**Comment by eniora** [comment]
Yep can confirm, it does nothing after the server is restarted after I enable it and if I set in settings to start with active live cam I get this after launching:

>Using provider ['CUDAExecutionProvider'] - Device:cuda
Traceback (most recent call last):
  File "C:\roop-unleashed\NEW VERSION\run.py", line 6, in <module>
    core.run()
  File "C:\roop-unleashed\NEW VERSION\roop\core.py", line 357, in run
    main.run()
  File "C:\roop-unleashed\NEW VERSION\ui\main.py", line 61, in run
    livecam_tab()
  File "C:\roop-unleashed\NEW VERSION\ui\tabs\livecam_tab.py", line 34, in livecam_tab
    cam.stream(on_stream_swap_cam, inputs=[cam, ui.globals.ui_selected_enhancer, ui.globals.ui_blend_ratio], outputs=[fake_cam_image], preprocess=True, postprocess=True, show_progress="hidden")
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\events.py", line 174, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 286, in set_event_trigger
    "inputs": [block._id for block in inputs],
  File "C:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 286, in <listcomp>
    "inputs": [block._id for block in inputs],
AttributeError: 'NoneType' object has no attribute '_id'

**Comment by C0untFloyd** [comment]
Should be fixed
