### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified with ffmpeg installed

### ISSUE THREAD

**Issue by AlexSham** [C0untFloyd/roop-unleashed#308]
Installed roop-unleashed using installer on win 11.
I am able to preview individual frames of the video at the bottom, with the face swap setting on. However, I get this error when pressing the start button with a video:

```
Creating 1014__temp.mp4 with 30.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '1920x1080', '-pix_fmt', 'bgr24', '-r', '30.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', 'E:\\Roop_Unleashed\\roop-unleashed\\output\\1014__temp.mp4']
Traceback (most recent call last):
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 503, in async_iteration
    return await iterator.__anext__()
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
  File "E:\Roop_Unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\Roop_Unleashed\roop-unleashed\ui\tabs\faceswap_tab.py", line 503, in start_swap
    batch_process(list_files_process, use_clip, clip_text, processing_method == "In-Memory processing", progress)
  File "E:\Roop_Unleashed\roop-unleashed\roop\core.py", line 302, in batch_process
    process_mgr.run_batch_inmem(v.filename, v.finalname, v.startframe, v.endframe, fps,roop.globals.execution_threads, skip_audio)
  File "E:\Roop_Unleashed\roop-unleashed\roop\ProcessMgr.py", line 208, in run_batch_inmem
    self.videowriter =  FFMPEG_VideoWriter(target_video, (width, height), fps, codec=roop.globals.video_encoder, crf=roop.globals.video_quality, audiofile=None)
  File "E:\Roop_Unleashed\roop-unleashed\roop\ffmpeg_writer.py", line 146, in __init__
    self.proc = sp.Popen(cmd, **popen_params)
  File "E:\Roop_Unleashed\installer_files\env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Roop_Unleashed\installer_files\env\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I tried ffmpeg -version and ffprobe -version both of this comands return proper results:

```
ffmpeg version 2023-06-21-git-1bcb8a7338-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      58. 13.101 / 58. 13.101
libavcodec     60. 21.100 / 60. 21.100
libavformat    60.  9.100 / 60.  9.100
libavdevice    60.  2.100 / 60.  2.100
libavfilter     9.  8.102 /  9.  8.102
libswscale      7.  3.100 /  7.  3.100
libswresample   4. 11.100 /  4. 11.100
libpostproc    57.  2.100 / 57.  2.100
```
I also checked PATH variables it also contains path to the ffmpeg: 
![image](https://github.com/C0untFloyd/roop-unleashed/assets/22525936/0c2ea201-332d-4167-8156-e047c172e296)

What can be the problem?

**Comment by RoombaVoid** [comment]
I've struggled with this before. Copying the ffmpeg files to the root of the roop folder finally fixed it. Roop has some path issues, couldnt be bothered....
![image](https://github.com/C0untFloyd/roop-unleashed/assets/144537801/99afc000-a2b6-4af0-bbb0-93bc26b5ad9c)

**Comment by AlexSham** [comment]
It solved the problem. Thank you!

**Comment by AlexSham** [comment]
It solved the problem. Thank you!

**Comment by Sakeeb2019** [comment]
it didn't fix the problem

**Comment by kutasos** [comment]
Nothing was working for me but I have found one solution that can be helpful also for you.

In system environment find ROOP Path and paste your ffmpeg files in that location.

<img width="366" alt="Zrzut ekranu 2024-04-20 164808" src="https://github.com/C0untFloyd/roop-unleashed/assets/52929620/573b2f76-92b5-4506-af7e-568891f741b1">

**Comment by AnderVicario** [comment]
i solved the problem, in my case i had to change "ffmpeg----" folder's name in installer/installer_file to fmpeg
![solution](https://github.com/C0untFloyd/roop-unleashed/assets/102811194/4eda0b6e-5392-4d78-ac45-d6d1d5aa539c)

**Comment by davioni** [comment]
i get an error FileNotFoundError: [WinError 2] The system cannot find the file specified '"roop unleashed""

**Comment by karlofdesigning** [comment]
can someone help me with this?

FFmpeg is already installed.
Skipping FFmpeg installation as it is already available.
Launching roop unleashed
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

Cloning into 'roop-unleashed'...
remote: Enumerating objects: 2981, done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 6711 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\roop-unleashed-main\roop-unleashed-main\installer\installer.py", line 78, in <module>
    install_dependencies()
  File "C:\Users\Admin\Desktop\roop-unleashed-main\roop-unleashed-main\installer\installer.py", line 37, in install_dependencies
    os.chdir(MY_PATH)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'roop-unleashed'

Done!
Press any key to continue . . .
