### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/workspace/roop-unleashed/temp/faceset/0.png'

### ISSUE THREAD

**Issue by nolanaatama** [C0untFloyd/roop-unleashed#312]
I got this error after clicking the create faceset file button (running on colab version):

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/roop-unleashed/ui/tabs/facemgr_tab.py", line 58, in on_faceset_changed
    util.unzip(filename, unzipfolder)
  File "/workspace/roop-unleashed/roop/utilities.py", line 263, in unzip
    zip_file.extractall(target_path)
  File "/usr/lib/python3.10/zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.10/zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/workspace/roop-unleashed/temp/faceset/0.png'

2 days ago I receive the same error first but later it works somehow, but I don't remember what I did to make it work

**Comment by nolanaatama** [comment]
so I got the error when I run the code on runpods, I tried it on google colab and it's working fine

**Comment by dnnagy** [comment]
I am getting the same error when running on a linux machine even after `running chmod -R 777 /workspace/roop-unleashed/temp/faceset/`
