### ISSUE TITLE
ERROR IN VIDEO OUTPUT "error An event handler (on_resultfiles_finished) didn't receive enough output values (needed: 2, received: 1). Wanted outputs: [image, video] Received outputs: [None]"

### ISSUE THREAD

**Issue by hamidtb** [C0untFloyd/roop-unleashed#328]
hi
when i want get video output i give flowing error:

Sorting videos/images
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Creating 0001__temp.mp4 with 30.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '1280x720', '-pix_fmt', 'bgr24', '-r', '30.0', '-an', '-i', '-', '-vcodec', 'libx265', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', 'E:\\AI\\roop-unleashed-3.2.0\\output\\0001__temp.mp4']
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 503, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\AI\roop-unleashed-3.2.0\ui\tabs\faceswap_tab.py", line 495, in start_swap
    batch_process(list_files_process, use_clip, clip_text, processing_method == "In-Memory processing", progress)
  File "E:\AI\roop-unleashed-3.2.0\roop\core.py", line 299, in batch_process
    process_mgr.run_batch_inmem(v.filename, v.finalname, v.startframe, v.endframe, fps,roop.globals.execution_threads, skip_audio)
  File "E:\AI\roop-unleashed-3.2.0\roop\ProcessMgr.py", line 208, in run_batch_inmem
    self.videowriter =  FFMPEG_VideoWriter(target_video, (width, height), fps, codec=roop.globals.video_encoder, crf=roop.globals.video_quality, audiofile=None)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\roop-unleashed-3.2.0\roop\ffmpeg_writer.py", line 146, in __init__
    self.proc = sp.Popen(cmd, **popen_params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1303, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1278, in validate_outputs
    raise ValueError(
ValueError: An event handler (on_resultfiles_finished) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [image, video]
Received outputs:
    [None]

Could you help please

**Comment by FrenchDoomer** [comment]
Hey,

Got the same issue today, by reinstalling it completely, it manages to fix it.

**Comment by hamidtb** [comment]
thanks
i use installer to,but get this error; if i don't mistake i use ```pip install -r requirements.txt``` command...
how to add ffmpeg manually at path?

**Comment by FrenchDoomer** [comment]
1. Installtion

> When you use installer, it creates an environment Conda. So no need to use pip it will do it automatically. But in the installer folder place a folder named roop-unleashed and all of the files in it. You will have like 2 time roop-unleashed. It's the only thing I managed to do to bypass this.
> 
> ![image](https://github.com/C0untFloyd/roop-unleashed/assets/148703298/d87aedc2-d3bb-465f-9d60-26bed3c746cd)

2. Ffmpeg and what I modified

a) Install Ffmpeg
> For ffmpeg if you use windows, I really recommend you to learn about Winget. Use this command, the last time I used it it added ffmpeg at path.
> 
> `winget install ffmpeg` <- it generally install it at the root of C:/
> 
> If after restart it didn't added it to path just follow this tutorial that seems really good.
> https://phoenixnap.com/kb/ffmpeg-windows
> Skip to step 3 to add to path.

b) Modify the batch file

> Remove this in windows_run.bat:
> `if not exist "%INSTALL_FFMPEG_DIR%" (
> 	echo Downloading ffmpeg from %FFMPEG_DOWNLOAD_URL% to %INSTALL_DIR%
>  	call curl -Lk "%FFMPEG_DOWNLOAD_URL%" > "%INSTALL_DIR%\ffmpeg.zip" || ( echo. && echo ffmpeg failed to download. && goto end )
> 	call powershell -command "Expand-Archive -Force '%INSTALL_DIR%\ffmpeg.zip' '%INSTALL_DIR%\'"
> 
> 	cd "installer_files"
> 	setlocal EnableExtensions EnableDelayedExpansion
> 
> 	for /f "tokens=*" %%f in ('dir /s /b /ad "ffmpeg*"') do (
> 		ren "%%f" "ffmpeg"
> 	)
> 	endlocal
> 	setx PATH "%INSTALL_FFMPEG_DIR%\bin\;%PATH%"
> 	echo To use videos, you need to restart roop after this installation. 
> 	cd ..
> )`
> 
> It will skip the check of the installation of ffmpeg in the file of Roop. Automatically it will use the one that you added to path.

Yep a lot of changes but it work fine for me with that.
