### ISSUE TITLE
Won't load target video on linux

### ISSUE THREAD

**Issue by alcarinque-istar** [C0untFloyd/roop-unleashed#33]
**Describe the bug**
After selecting the target video, and entering the frame number with the face to swap nothing happens. The number of frames is ok, so the video is loading. Console shows this tkinter error:
`Traceback (most recent call last):
  File "/home/alcarinque/.conda/envs/roop/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/alcarinque/.conda/envs/roop/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/media/Yhanthlei/roop-unleashed/roop-unleashed/roop/ui.py", line 69, in <lambda>
    target_button = ctk.CTkButton(root, text='Select target image/video', width=IMAGE_BUTTON_WIDTH, height=IMAGE_BUTTON_HEIGHT, compound='top', anchor='center', command=lambda: select_target_path())
  File "/media/Yhanthlei/roop-unleashed/roop-unleashed/roop/ui.py", line 232, in select_target_path
    show_face_selection(OUTPUT_FACES_DATA, False)
  File "/media/Yhanthlei/roop-unleashed/roop-unleashed/roop/ui.py", line 400, in show_face_selection
    ROOT.wm_attributes('-disabled', True)
  File "/home/alcarinque/.conda/envs/roop/lib/python3.10/tkinter/__init__.py", line 2005, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-disabled": must be -alpha, -topmost, -zoomed, -fullscreen, or -type
`

Probably an error with the tkinter version in linux? Works fine on windows. 

**To Reproduce**
1. Click  'Select image with face', and select source face
2. Click on 'Select target image/vide' and select target video
3. Enter number of frame
4. See error on console. Image does not appear in pSelect target button

**Details**
What OS are you using?
- [X] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [X ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide

**Comment by C0untFloyd** [comment]
> Probably an error with the tkinter version in linux? Works fine on windows.

Yes, unfortunately you're right:
https://github.com/PySimpleGUI/PySimpleGUI/issues/1799

I'm about to port this whole thing to another UI framework but until then you could comment out line 400 in ui.py like this:
`#ROOT.wm_attributes('-disabled', True)`
