### ISSUE TITLE
Failed inference for CodeFormer

### ISSUE THREAD

**Issue by mammuthus** [C0untFloyd/roop-unleashed#34]
**Describe the bug**
CodeFormer face enhancement method causing an error

**To Reproduce**
- Run roop-unleashed with:
`python run.py --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9 -f C:\Users\omavel\Desktop\roopFake\output\unleashed`
- Switch on "Keep fps" option
- Choose Codeformer as enhancement engine
- Press "Start"
- After some calculation, an error message appeared:
```
Downloading: "https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/parsing_parsenet.pth" to C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop-unleashed\lib\site-packages\codeformer\weights\facelib\parsing_parsenet.pth

100%|███████████████████████████████████████████████████████████████████████████████████████████████| 81.4M/81.4M [01:13<00:00, 1.17MB/s]
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same:00, 1.16MB/s]
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Processing:   0%|                                                                                             | 0/449 [02:49<?, ?frame/s]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop-unleashed\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop\ui.py", line 104, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', command=lambda: select_output_path(start))
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop\ui.py", line 270, in select_output_path
    start()
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop\core.py", line 201, in start
    frame_processor.process_video(roop.globals.SELECTED_FACE_DATA_INPUT, roop.globals.SELECTED_FACE_DATA_OUTPUT, temp_frame_paths)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop\processors\frame\face_enhancer.py", line 94, in process_video
    roop.processors.frame.core.process_video(source_face, target_face, temp_frame_paths, process_frames)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop\processors\frame\core.py", line 88, in process_video
    multi_process_frame(False, source_face, target_face, frame_paths, process_frames, lambda: update_progress(progress))
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop\processors\frame\core.py", line 60, in multi_process_frame
    future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop\processors\frame\face_enhancer.py", line 74, in process_frames
    result = process_frame(None, temp_frame)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop\processors\frame\face_enhancer.py", line 66, in process_frame
    temp_frame = enhance_face(temp_frame)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop\processors\frame\face_enhancer.py", line 60, in enhance_face
    temp_frame = Image.blend(temp_frame_original, Image.fromarray(temp_frame), 0.5)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop-unleashed\lib\site-packages\PIL\Image.py", line 3078, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'

```

Details
What OS are you using?
✅ Windows

Are you try to use a GPU?
✅ Intel CPU

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/49b37bc9-e697-4647-8bbd-f5a028e3ec3a)

**Sanity Check**
✅ I have the latest code from the github repository
✅ I have followed the installation guide

**Comment by C0untFloyd** [comment]
`C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop-unleashed\lib\site-packages\codeformer\weights\facelib\parsing_parsenet.pth` is an aweful long path and might break windows path limits. Could you try installing to a shorter path? Other than that, you're using Python 3.9, I'm developing using 3.10. Perhaps updating might also help.

**Comment by Heislerink** [comment]
There’s a way to extend path size in Windows. https://www.thewindowsclub.com/how-to-enable-or-disable-win32-long-paths-in-windows-11-10Jeff HeislerOn Jul 10, 2023, at 4:54 PM, C0untFloyd ***@***.***> wrote:﻿
C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop-unleashed\roop-unleashed\roop-unleashed\lib\site-packages\codeformer\weights\facelib\parsing_parsenet.pth is an aweful long path and might break windows path limits. Could you try installing to a shorter path? Other than that, you're using Python 3.9, I'm developing using 3.10. Perhaps updating might also help.

**Comment by mammuthus** [comment]
`an aweful long path and might break windows path limits`
Same error, didn't help.
Will try to run with 3.10

**Comment by mammuthus** [comment]
Same error with 3.10
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/bdfd4da7-794f-4f98-ad73-9e55f36586b5)
```
(venv_unleashed) C:\Users\omavel\Desktop\roopFake\roop-unleashed>python run.py --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9
Loading roop.processors.frame.face_swapper
Loading roop.processors.frame.face_enhancer
2023-07-13T16:56:50.568ZE [4900:NonCelloThread] thumbnail_util_win.cc:115:LoadBitmapFromPngResource Can't find PNG resource 0.
2023-07-13T16:56:50.568ZI [4900:NonCelloThread] ctxmenu.cc:213:GenerateContextMenu Received context menu with 0 menu items.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\omavel/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\omavel/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\omavel/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\omavel/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\omavel/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\omavel\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\venv_unleashed\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\ui.py", line 104, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', command=lambda: select_output_path(start))
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\ui.py", line 262, in select_output_path
    elif is_video(roop.globals.target_path) or has_extension(roop.globals.target_path, ['gif']) == True:
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\utilities.py", line 123, in has_extension
    return filepath.lower().endswith(tuple(extensions))
AttributeError: 'NoneType' object has no attribute 'lower'
2023-07-13T16:57:52.489ZE [4900:NonCelloThread] thumbnail_util_win.cc:115:LoadBitmapFromPngResource Can't find PNG resource 0.
2023-07-13T16:57:52.490ZI [4900:NonCelloThread] ctxmenu.cc:213:GenerateContextMenu Received context menu with 0 menu items.
2023-07-13T16:58:20.998ZE [4900:NonCelloThread] thumbnail_util_win.cc:115:LoadBitmapFromPngResource Can't find PNG resource 0.
2023-07-13T16:58:20.999ZI [4900:NonCelloThread] ctxmenu.cc:213:GenerateContextMenu Received context menu with 0 menu items.
[ROOP.CORE] Creating temp resources...
[ROOP.CORE] Extracting frames...
[ROOP.CORE] ROOP.FACE-SWAPPER in progress...
Processing:   0%|                                                                           | 0/812 [00:00<?, ?frame/s]Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Processing: 100%|█| 812/812 [08:08<00:00,  1.66frame/s, memory_usage=02.87GB, execution_providers=['CPUExecutionProvide
[ROOP.CORE] ROOP.FACE-ENHANCER in progress...
Processing:   0%|                                                                           | 0/812 [00:00<?, ?frame/s]Downloading: "https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/detection_Resnet50_Final.pth" to C:\Users\omavel\Desktop\roopFake\roop-unleashed\venv_unleashed\lib\site-packages\codeformer\weights\facelib\detection_Resnet50_Final.pth

100%|███████████████████████████████████████████████████████████████████████████████| 104M/104M [01:35<00:00, 1.15MB/s]
Downloading: "https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/parsing_parsenet.pth" to C:\Users\omavel\Desktop\roopFake\roop-unleashed\venv_unleashed\lib\site-packages\codeformer\weights\facelib\parsing_parsenet.pth

100%|█████████████████████████████████████████████████████████████████████████████| 81.4M/81.4M [01:14<00:00, 1.15MB/s]
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Processing:   0%|                                                                           | 0/812 [02:54<?, ?frame/s]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\omavel\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\venv_unleashed\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\ui.py", line 104, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', command=lambda: select_output_path(start))
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\ui.py", line 270, in select_output_path
    start()
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\core.py", line 201, in start
    frame_processor.process_video(roop.globals.SELECTED_FACE_DATA_INPUT, roop.globals.SELECTED_FACE_DATA_OUTPUT, temp_frame_paths)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\processors\frame\face_enhancer.py", line 94, in process_video
    roop.processors.frame.core.process_video(source_face, target_face, temp_frame_paths, process_frames)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\processors\frame\core.py", line 88, in process_video
    multi_process_frame(False, source_face, target_face, frame_paths, process_frames, lambda: update_progress(progress))  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\processors\frame\core.py", line 60, in multi_process_frame
    future.result()
  File "C:\Users\omavel\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\omavel\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\omavel\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\processors\frame\face_enhancer.py", line 74, in process_frames
    result = process_frame(None, temp_frame)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\processors\frame\face_enhancer.py", line 66, in process_frame
    temp_frame = enhance_face(temp_frame)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\roop\processors\frame\face_enhancer.py", line 60, in enhance_face
    temp_frame = Image.blend(temp_frame_original, Image.fromarray(temp_frame), 0.5)
  File "C:\Users\omavel\Desktop\roopFake\roop-unleashed\venv_unleashed\lib\site-packages\PIL\Image.py", line 3078, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
```

**Comment by lysxelapsed** [comment]
I could be wrong, but I tried to run the original roop in venv with my first install, and failed - I'm fairly new to python. But shouldn't the roop folder be located **inside** the venv? I thought that this is where I went wrong back then (didn't try again with venv tho), and got a similar error.

**Comment by BadBoy7561** [comment]
For what it's worth, I'm having the same issue. I'm using Python 3.10 as well. Here's the last bit of code from the command window that I get:

```
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
[ROOP.CORE] ROOP.FACE-ENHANCER in progress...
Failed inference for CodeFormer: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\Documents\Programs\roop_unleashed_win\installer_files\env\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\user\Documents\Programs\roop_unleashed_win\installer_files\env\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\user\Documents\Programs\roop_unleashed_win\roop-unleashed\roop\ui.py", line 104, in <lambda>
    start_button = ctk.CTkButton(root, text='Start', command=lambda: select_output_path(start))
  File "C:\Users\user\Documents\Programs\roop_unleashed_win\roop-unleashed\roop\ui.py", line 270, in select_output_path
    start()
  File "C:\Users\user\Documents\Programs\roop_unleashed_win\roop-unleashed\roop\core.py", line 181, in start
    frame_processor.process_image(roop.globals.SELECTED_FACE_DATA_INPUT, roop.globals.SELECTED_FACE_DATA_OUTPUT, target, roop.globals.output_path)
  File "C:\Users\user\Documents\Programs\roop_unleashed_win\roop-unleashed\roop\processors\frame\face_enhancer.py", line 88, in process_image
    result = process_frame(None, target_frame)
  File "C:\Users\user\Documents\Programs\roop_unleashed_win\roop-unleashed\roop\processors\frame\face_enhancer.py", line 66, in process_frame
    temp_frame = enhance_face(temp_frame)
  File "C:\Users\user\Documents\Programs\roop_unleashed_win\roop-unleashed\roop\processors\frame\face_enhancer.py", line 60, in enhance_face
    temp_frame = Image.blend(temp_frame_original, Image.fromarray(temp_frame), 0.5)
  File "C:\Users\user\Documents\Programs\roop_unleashed_win\installer_files\env\lib\site-packages\PIL\Image.py", line 3078, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
```

**Comment by mammuthus** [comment]
Based on what I've noticed, this issue occurs exclusively when **specific** face pictures are used as source images. Even though the face replacement is executed successfully, an error appears when enhancing **certain** faces.

**Comment by eniora** [comment]
I fixed this error back then by enabling CUDA, for some reason codeformer requires GPU processor to be set, it doesn't work on CPU. Try adding **--execution-provider cuda** to the command line argument.

**Comment by mammuthus** [comment]
Yes, i know, with CUDA it works (barely lol). But the current issue I'm addressing involves using the CPU.

**Comment by phineas-pta** [comment]
error is this: `Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

so codeformer auto detect cuda and try to use cuda

@C0untFloyd u need to specify `device`

**Comment by C0untFloyd** [comment]
Closed all old issues because of new rewritten version.
