### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models/CLIP/rd64-uni-refined.pth'

### ISSUE THREAD

**Issue by Gago3000** [C0untFloyd/roop-unleashed#362]
**Describe the bug**
When I try to use clip2seg text masking, I get an error saying: FileNotFoundError: [Errno 2] No such file or directory: 'models/CLIP/rd64-uni-refined.pth'. The file is in the mentioned directory. I have no clue why this is suddenly happening. It's been a while since I used Roop-unleashed. I have zero clue what changes that I did with using my Mac that might have caused this. I tried switching between coreml and cpu but it doesn't change anything.

It's my first time ever writing anything on Github so please excuse any mistakes I might be doing here. Thank you!

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ x ] Mac

Are you using a GPU?
- [ x ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ x ] Mac

**Which version of roop unleashed are you using?**
roop unleashed 3.3.4

Terminal output:

(base) user@MPB ~ % Cd roop-unleashed
PYTORCH_ENABLE_MPS_FALLBACK=1 python /Users/user/roop-unleashed/run.py
Using provider ['CPUExecutionProvider'] - Device:cpu
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Forcing CPU for Face Analysis
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/user/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Sorting videos/images
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Traceback (most recent call last):
  File "/Users/user/miniforge3/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/user/miniforge3/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/Users/user/miniforge3/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/user/miniforge3/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/Users/user/miniforge3/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/user/miniforge3/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/user/miniforge3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/user/miniforge3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/user/miniforge3/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/Users/user/miniforge3/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/user/roop-unleashed/ui/tabs/faceswap_tab.py", line 503, in start_swap
    batch_process(list_files_process, use_clip, clip_text, processing_method == "In-Memory processing", progress)
  File "/Users/user/roop-unleashed/roop/core.py", line 249, in batch_process
    process_mgr.initialize(roop.globals.INPUT_FACESETS, roop.globals.TARGET_FACES, options)
  File "/Users/user/roop-unleashed/roop/ProcessMgr.py", line 87, in initialize
    p.Initialize(devicename)
  File "/Users/user/roop-unleashed/roop/processors/Mask_Clip2Seg.py", line 30, in Initialize
    self.model_clip.load_state_dict(torch.load('models/CLIP/rd64-uni-refined.pth', map_location=torch.device('cpu')), strict=False)
  File "/Users/user/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/user/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/user/miniforge3/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/CLIP/rd64-uni-refined.pth'

**Comment by Gago3000** [comment]
Thanks for the fast reply! That worked perfectly!
