### ISSUE TITLE
DMDNet doesn't work with DirectML giving CUDA error

### ISSUE THREAD

**Issue by YW5555** [C0untFloyd/roop-unleashed#367]
**Describe the bug**
When trying to process video with DMDNet post-processing, a CUDA error pops up due to using DirectML. I'm assuming DMDNet doesn't support DirectML yet?

**To Reproduce**

1. Run faceswap with DMDNet as the post-processor.

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [X] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
**roop unleashed 3.3.4**

```
Applied providers: ['DmlExecutionProvider', 'CPUExecutionProvider'], with options: {'DmlExecutionProvider': {}, 'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
Traceback (most recent call last):
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1109, in call_function    prediction = await anyio.to_thread.run_sync(
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run    result = context.run(func, *args)
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "Z:\roop-unleashed\installer\roop-unleashed\ui\tabs\faceswap_tab.py", line 389, in on_preview_frame_changed
    current_frame = live_swap(current_frame, roop.globals.face_swap_mode, use_clip, clip_text, SELECTED_INPUT_FACE_INDEX)
  File "Z:\roop-unleashed\installer\roop-unleashed\roop\core.py", line 189, in live_swap
    process_mgr.initialize(roop.globals.INPUT_FACESETS, roop.globals.TARGET_FACES, options)
  File "Z:\roop-unleashed\installer\roop-unleashed\roop\ProcessMgr.py", line 87, in initialize
    p.Initialize(devicename)
  File "Z:\roop-unleashed\installer\roop-unleashed\roop\processors\Enhance_DMDNet.py", line 32, in Initialize
    self.model_dmdnet = self.create(devicename)
  File "Z:\roop-unleashed\installer\roop-unleashed\roop\processors\Enhance_DMDNet.py", line 197, in create
    weights = torch.load('./models/DMDNet.pth')
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\torch\serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\torch\serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "Z:\roop-unleashed\installer\installer_files\env\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by aldemoth** [comment]
Replacing line 197 of "roop-unleashed\roop\processors\Enhance_DMDNet.py" file solves the problem. 

Original line:
```
    weights = torch.load('./models/DMDNet.pth') 
```
Fixed:
```
    weights = torch.load('./models/DMDNet.pth', map_location=self.torchdevice) 
```
This is CPU only. I didn't try implementing DirectML because I have no space in my ssd currently.

**Comment by arunhk3** [comment]
But the change lead to the below error:

Using provider ['CPUExecutionProvider'] - Device:cpu
Running on local URL:  http://127.0.0.1:7860
INFO:httpx:HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
INFO:httpx:HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
INFO:httpx:HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
Forcing CPU for Face Analysis
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\AI\Roop\roop-unleashed\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\AI\Roop\roop-unleashed\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\AI\Roop\roop-unleashed\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\AI\Roop\roop-unleashed\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\AI\Roop\roop-unleashed\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Forcing CPU for Face Analysis
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\AI\Roop\roop-unleashed\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\AI\Roop\roop-unleashed\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\AI\Roop\roop-unleashed\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: H:\AI\Roop\roop-unleashed\models\buffalo_l\genderage.onnx genderage
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\AI\Roop\roop-unleashed\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Traceback (most recent call last):
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\gradio\blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\gradio\utils.py", line 805, in wrapper
    response = f(*args, **kwargs)
  File "H:\AI\Roop\roop-unleashed\ui\tabs\faceswap_tab.py", line 469, in on_preview_frame_changed
    current_frame = live_swap(current_frame, options)
  File "H:\AI\Roop\roop-unleashed\roop\core.py", line 201, in live_swap
    newframe = process_mgr.process_frame(frame)
  File "H:\AI\Roop\roop-unleashed\roop\ProcessMgr.py", line 330, in process_frame
    num_swapped, temp_frame = self.swap_faces(frame, temp_frame)
  File "H:\AI\Roop\roop-unleashed\roop\ProcessMgr.py", line 396, in swap_faces
    temp_frame = self.process_face(self.options.selected_index, face, temp_frame)
  File "H:\AI\Roop\roop-unleashed\roop\ProcessMgr.py", line 559, in process_face
    enhanced_frame, scale_factor = p.Run(self.input_face_datas[face_index], target_face, fake_frame)
  File "H:\AI\Roop\roop-unleashed\roop\processors\Enhance_DMDNet.py", line 44, in Run
    result = self.enhance_face(source_faceset, temp_frame, target_face)
  File "H:\AI\Roop\roop-unleashed\roop\processors\Enhance_DMDNet.py", line 154, in enhance_face
    SpMem256, SpMem128, SpMem64 = self.model_dmdnet.generate_specific_dictionary(sp_imgs = SpecificImgs.to(self.torchdevice), sp_locs = SpecificLocs)
  File "H:\AI\Roop\roop-unleashed\roop\processors\Enhance_DMDNet.py", line 871, in generate_specific_dictionary
    return self.memorize(sp_imgs, sp_locs)
  File "H:\AI\Roop\roop-unleashed\roop\processors\Enhance_DMDNet.py", line 701, in memorize
    fs = self.E_hq(img, locs)
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\AI\Roop\roop-unleashed\roop\processors\Enhance_DMDNet.py", line 575, in forward
    le_part_64 = roi_align_self(f6_1.clone(), le_location//8, self.part_sizes[0]//8)
  File "H:\AI\Roop\roop-unleashed\roop\processors\Enhance_DMDNet.py", line 482, in roi_align_self
    return torch.cat([F.interpolate(input[i:i+1,:,location[i,1]:location[i,3],location[i,0]:location[i,2]],test,mode='bilinear',align_corners=False) for i in range(input.size(0))],0)
  File "H:\AI\Roop\roop-unleashed\roop\processors\Enhance_DMDNet.py", line 482, in <listcomp>
    return torch.cat([F.interpolate(input[i:i+1,:,location[i,1]:location[i,3],location[i,0]:location[i,2]],test,mode='bilinear',align_corners=False) for i in range(input.size(0))],0)
  File "C:\Users\t0rna\miniconda3\envs\roop\lib\site-packages\torch\nn\functional.py", line 4020, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
**RuntimeError: Input and output sizes should be greater than 0, but got input (H: 1, W: 0) output (H: 10, W: 10)**

**Comment by Mejituu** [comment]
> Replacing line 197 of "roop-unleashed\roop\processors\Enhance_DMDNet.py" file solves the problem.
> 
> Original line:
> 
> ```
>     weights = torch.load('./models/DMDNet.pth') 
> ```
> 
> Fixed:
> 
> ```
>     weights = torch.load('./models/DMDNet.pth', map_location=self.torchdevice) 
> ```
> 
> This is CPU only. I didn't try implementing DirectML because I have no space in my ssd currently.

DML Good
