### ISSUE TITLE
class_ Error - Mask_Clip2Seg does not exist

### ISSUE THREAD

**Issue by Dean-Corso** [C0untFloyd/roop-unleashed#416]
Hi guys,

**Describe the bug**
Just have a problem to use the Text Masking / Show Mask Preview. It does not work and I get this error each time in browser...
`error
local variable 'class_' referenced before assignment`
...and in terminal I get this error output...
```
Module roop.processors.Mask_Clip2Seg does not exist
Traceback (most recent call last):
  File "C:\roop_unleashed\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\roop_unleashed\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\roop_unleashed\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\roop_unleashed\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\roop_unleashed\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\roop_unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\roop_unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\roop_unleashed\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "C:\roop_unleashed\roop-unleashed\ui\tabs\faceswap_tab.py", line 435, in on_preview_mask
    current_frame = preview_mask(current_frame, clip_text)
  File "C:\roop_unleashed\roop-unleashed\roop\core.py", line 206, in preview_mask
    process_mgr.initialize(roop.globals.INPUT_FACESETS, roop.globals.TARGET_FACES, options)
  File "C:\roop_unleashed\roop-unleashed\roop\ProcessMgr.py", line 88, in initialize
    p = str_to_class(module, classname)
  File "C:\roop_unleashed\roop-unleashed\roop\utilities.py", line 218, in str_to_class
    return class_ or None
UnboundLocalError: local variable 'class_' referenced before assignment
```
...so not sure what the problem is. The Mask_Clip2Seg.py file present in "C:\roop_unleashed\roop-unleashed\roop\processors\" folder of my virtual env. How to fix that problem? Do I have to install anything more as written in the requirements file? If yes what and how is the pip command for it?

**To Reproduce**
1. Just run roop-unleashed via terminal - run.py
2. In browser just load any target image you can see in preview window (right side above)
3. Check the "Use Text Masking checkbox"
5. Click on "Show Mask Preview"
6. Now you get the error box in browser to see

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac
- [ x] System CPU

**Which version of roop unleashed are you using?**
3.5.0
**Screenshots**

**Comment by C0untFloyd** [comment]
Oh it could be because you're using CPU-only. I'm unsure if I've ever tested it without GPU.

**Comment by Dean-Corso** [comment]
Hello @C0untFloyd,

so maybe you could try it by yourself running the app only with CPU setting. Would be nice if you could find & fix that problem to make that masking function work for CPU users too.

Off Topic: What GPU I have to use to render a video in a short time? Are there any recommendations? Just would like to know and find out what to use. So maybe some of you users of roop-unleashed could post some info's about your GPU spec and how long it takes to render a video ~round about.

Example Task: Any standard Video (60 seconds long) in h264 / AVC / 720p / 30 fps using any Model except none. How much time does it take for you? Just trying to find out some average values to get an better feeling what GPU I would need to use later. Some info's about that be helpfully for me.

**Comment by Oil3** [comment]
@Dean-Corso nobody here is at your service.

It works fine for CPU, for GPU, and even uses mac silicon's GPU (if change bicubic to bilinear in the code).
Download pytorch again.
no good?
download roopunleashed again
no good?  tell us version of python, onnxruntime, onnx, pytorch, windows and any you think of relevant

In reference to the "off topic" questions, what you ask is very subjective.

I would answer ditch the windows and get an imac, macmini, or macbookpro, but others would disagree.

We are bordeline with machine learning technology in this app, and although it's been years, we are still at the infancy, when someone has the nerves to assemble a proper asic board, videogaming GPU that have an advantage today might get ridiculed, facing a 1000% speed increase at a minus 1000% cost. ANyway, you have to be on mac to recommend mac but I use any non living machines (and living if it has tits):
Nvidia seems to have quite a grip on our sector, are very cocky about it and overpice as much as oversize their equipements, but,
Ceteris paribus, "get the 2nd best nvidia card you can afford" is the answer to satisfy your needs now

And if you are native english speaker, dude, drop the attitude

**Comment by Disorbs** [comment]
im getting the same thing and im using cuda :/

**Comment by Oil3** [comment]
I downloaded all mentioned files, tried with cpu, and the mask always works. I tried removing the model file, and it was redow nloaded by Unleashed at start.
I could reproduce the exact same error, by changing the name of "Mask_Clip2Seg.py".
Try making a new text file and copy paste the content of "Mask_Clip2Seg.py'.
Idea here is to assumee somthing is wrong with "Mask_Clip2Seg.py ", and remove the old on, and make a new one.
To make sure it's the correct format, you can duplicate anotber .py and paste into it, or doxwnload raw from https://github.com/C0untFloyd/roop-unleashed/raw/main/roop/processors/Mask_Clip2Seg.py

the first line "Module roop.processors.Mask_Clip2Seg does not exist" is very direct, but we don't know if its "file not found" or "file corrupted", so remvoe it, make it again.
mine is there, and I start run.py from my home folder and I have no whitespace nowhere;
[root/homefolder]/roop-unleashed/roop/processors/Mask_Clip2Seg.py

**Comment by C0untFloyd** [comment]
Grasping at straws here, but could it be that the rwx file attributes are wrong with that file (perhaps disallowing reads/execution)?
Also you're on Linux, aren't you?  Perhaps try renaming the file to all lowercase...please let us know if you could find out anything.

**Comment by lysxelapsed** [comment]
could changing the local variable 'class_' to a global variable be a solution?

https://sabe.io/blog/python-local-variable-referenced-before-assignment

**Comment by Dean-Corso** [comment]
Hey guys,

I'm using Windows 10 x64 not Linux. So why should it make any sense to change the name to lowercase? All other py files aren't in LC at all. But I tried this too to change the filename from "Mask_Clip2Seg.py" to "mask_clip2seg.py" and getting the same error. So what does it mean now? The file is there in the right folder but the app is telling me...
```
UnboundLocalError: local variable 'class_' referenced before assignment
Module roop.processors.Mask_Clip2Seg does not exist
Traceback (most recent call last):
....
  File "C:\roop_unleashed\roop-unleashed\roop\utilities.py", line 218, in str_to_class
    return class_ or None
```
...are that 2 errors? Variable class_ referenced issue + Mask_Clip2Seg not exist? By the way, the variable called "class_" in the utilities.py is NOT referenced before assignment its only set on time in the procedere...
```
def str_to_class(module_name, class_name):
    from importlib import import_module
    try:
        module_ = import_module(module_name)
        try:
            class_ = getattr(module_, class_name)()
        except AttributeError:
            print(f'Class {class_name} does not exist')
    except ImportError:
        print(f'Module {module_name} does not exist')
    return class_ or None
```
...under try command and before is nothing set. Also this variable class_ is just used in this utilities.py file only. Something does not work correctly in this case. The output error seems to be wrong in my opinion or what do you think? I'm not into python language so you should know it better. What can I do now to make it work? So the app itself seems to work doing some face swap etc only this mask preview fails always. I do just enable (check) the Use Text Masking (after loading source & target images) and below I just let the text like it is (cup,hands,hair,banana) and press Show Mask Preview = Error.

I also tried to add the "global class_" one line before the try: command (on fly) but get still same error. No idea what the problem is. I'm using Windows & CPU instead of GPU in settings. Anyone using same settings?

**Comment by C0untFloyd** [comment]
The problem is this:
Module roop.processors.Mask_Clip2Seg does not exist

You could get rid of the UnboundLocalError blabla by adding
`class_ = None`
above the first `try:` (this is a bug but it doesn't matter much).
The file can't be found or parsed. I currently have no solution for this, I'm sorry.

**Comment by Dean-Corso** [comment]
Hi @C0untFloyd,

so I did what you said to change the utilities.py to this...
```
def str_to_class(module_name, class_name):
    from importlib import import_module
    class_ = None
    try:
        module_ = import_module(module_name)
        try:
            class_ = getattr(module_, class_name)()
        except AttributeError:
            print(f'Class {class_name} does not exist')
    except ImportError:
        print(f'Module {module_name} does not exist')
    return class_ or None
```
...and now I get a other / similar error....

```
Module roop.processors.Mask_Clip2Seg does not exist
Traceback (most recent call last):
  File "C:\roop_unleashed\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\roop_unleashed\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\roop_unleashed\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\roop_unleashed\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\roop_unleashed\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\roop_unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\roop_unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\roop_unleashed\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "C:\roop_unleashed\roop-unleashed\ui\tabs\faceswap_tab.py", line 435, in on_preview_mask
    current_frame = preview_mask(current_frame, clip_text)
  File "C:\roop_unleashed\roop-unleashed\roop\core.py", line 206, in preview_mask
    process_mgr.initialize(roop.globals.INPUT_FACESETS, roop.globals.TARGET_FACES, options)
  File "C:\roop_unleashed\roop-unleashed\roop\ProcessMgr.py", line 89, in initialize
    p.Initialize(devicename)
AttributeError: 'NoneType' object has no attribute 'Initialize'
```
...what now?

**Comment by C0untFloyd** [comment]
No idea, I'm sorry. The only option left to check would be the file attributes of Mask_Clip2Seg.py

**Comment by Dean-Corso** [comment]
Hi again,

so the attribute isn't the problem so its same like all other files (A). I just don't understand why its telling me the file does not exist. So when I choose the GPEN model (Enhance_GPEN.py) and do rename the file to "_Enhance_GPEN" and press on refresh button then I get also the same error about this file...
`Module roop.processors.Enhance_GPEN does not exist`
...and when I rename it back to original and press refresh button again then it works doing the face swap with GPEN. This file is also in same folder as the Mask_Clip2Seg.py. Just don't get it. 😞

**Comment by lysxelapsed** [comment]
Have you looked at this solution? -> #362
Not the exact same error message and regarding the pth-file, but _could_ be the same issue: That it's looking for the file in the wrong place.
Or could it be as simple as #340 ?

**Comment by Dean-Corso** [comment]
Hello @lysxelapsed,

what to enter as path of "/Users/User" in my case?
`C:\roop_unleashed\roop-unleashed\models\CLIP\`
So I tried different path versions to change them on fly and pressing on "Show Mask Preview" again...
```
self.model_clip.load_state_dict(torch.load('/Users/user/models/CLIP/rd64-uni-refined.pth', map_location=torch.device('cpu')), strict=False)
or
self.model_clip.load_state_dict(torch.load('/roop_unleashed/roop-unleashed/models/CLIP/rd64-uni-refined.pth', map_location=torch.device('cpu')), strict=False)
```
...but without success. I still get the error. By the way, yesterday I did update some py files so I have seen @C0untFloyd did update the repo. After the manually update of few files I get a other error message name called "AttributeError: 'NoneType' object has no attribute 'Run'" but seems to be same only other error name so I still get the top error "Module roop.processors.Mask_Clip2Seg does not exist". Below the full error...

```
Module roop.processors.Mask_Clip2Seg does not exist
Not using roop.processors.Mask_Clip2Seg
Traceback (most recent call last):
  File "C:\roop_unleashed\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\roop_unleashed\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\roop_unleashed\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\roop_unleashed\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\roop_unleashed\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\roop_unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\roop_unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\roop_unleashed\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "C:\roop_unleashed\roop-unleashed\ui\tabs\faceswap_tab.py", line 435, in on_preview_mask
    current_frame = preview_mask(current_frame, clip_text)
  File "C:\roop_unleashed\roop-unleashed\roop\core.py", line 210, in preview_mask
    return process_mgr.process_mask(maskprocessor, frame, maskimage)
  File "C:\roop_unleashed\roop-unleashed\roop\ProcessMgr.py", line 587, in process_mask
    img_mask = processor.Run(frame, self.options.masking_text)
AttributeError: 'NoneType' object has no attribute 'Run'
```
About installing, so I just installed the requirements (pip install -r requirements.txt and also had to install insightface-0.7.3-cp310-cp310-win_amd64.whl) in the file. So the torchvision is there...
C:\roop_unleashed\Lib\site-packages\torchvision
...and clipseg is here...
C:\roop_unleashed\roop-unleashed\clip\clipseg.py

...so what should I do to get it finally working?

**Comment by lysxelapsed** [comment]
> self.model_clip.load_state_dict(torch.load('/roop_unleashed/roop-unleashed/models/CLIP/rd64-uni-refined.pth', map_location=torch.device('cpu')), strict=False)

That looks about right for your folder structure, but maybe it's another file. In his case, changing to the "whole" Path (except the "C:" worked, but the error output was a bit more clear. Sorry that it's not working for you. That's all I got 🤷‍♂️

**Comment by C0untFloyd** [comment]
Perhaps reinstalling everything with very short foldernames might be worth a try too. There's this max path length in windows...I know, still grasping at straws.

**Comment by Dean-Corso** [comment]
Hi guys,

short folder names? Windows using MAX_PATH = 260 bytes and my own created project folder is already pretty short...
`C:\roop_unleashed\`
...and shouldn't be the problem about that error I get. Otherwise the other files in same folder like Enhance_GPEN are read without any problem.

So this project folder of "roop_unleashed" has a size of ~10 GB and to create a new virtual environment for same project I have not enough free space yet. So what I can do is to post my installing step list and hope that anyone of you could try to install roop on same way under Windows 10 (x64) OS on your main system if you do use it too like me or in a VM etc if possible.

```
Installing roop-unleashed (I had to do different steps to get roop successfully installed)
------------------------------------------
https://github.com/C0untFloyd/roop-unleashed/

python -m venv roop_unleashed
cd roop_unleashed
Scripts\activate.bat
git clone https://github.com/C0untFloyd/roop-unleashed
cd roop-unleashed
python -m pip install --upgrade pip		// optional
pip install -r requirements.txt

Durring the installation I got error about python version and I have to install 
python version 3.10.0 on main OS and change the path in variables of system to 310.
Now I did same steps again...

cd roop_unleashed
Scripts\activate.bat
cd roop-unleashed
pip install -r requirements.txt

Then I got some CMAKE path error because it was not installed. I installed it...
https://cmake.org/download
cmake-3.28.1-windows-x86_64.zip

C:\YourPath\cmake-3.28.1-windows-x86_64\bin\

...and added the path into system variables and then I did start again from start....

cd roop_unleashed
Scripts\activate.bat
cd roop-unleashed
pip install -r requirements.txt

Then I got this errors....
-----
WARNING: Built wheel for insightface is invalid: Wheel has unexpected file name: expected 'insightface', got 'UNKNOWN'

Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
------

....and some internet search told me this link...
https://github.com/Gourieff/sd-webui-reactor#insightfacebuild
...to download the file
https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl
...and to copy it into env folder of this project and to install it so I did this....

cd roop_unleashed
Scripts\activate.bat
cd roop-unleashed
pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
pip install -r requirements.txt

Now installing was working till end and app did open in browser when I did enter

python run.py
```
So as you can see I had some trouble during the installing process but finally I got it working. After this I created a quick batch files to run roop...
```
::@echo off
cd\
cd roop_unleashed
call "Scripts\activate.bat"
cd roop-unleashed
python run.py
pause
exit
```
...in the settings of roop I did choose CPU because I don't have any good GPU card yet. Then I was just loading any single target image and a face swap image (optional) and checked the "Use Text Masking" and clicked on Show Mask Preview and then I got those error X I told already all the time in my pre posts. That's all what I did. Now tell me, what did I wrong? The face swap function is working without problem only when I have checked the "Use Text Masking" it will fail or clicking on the "Show Mask Preview" button etc. I left that words in the text edit control "cup,hands,hair,banana" and it fails. Also when I enter any other words it fails. So I just clueless at this point and need some help with it to get this mask feature working.

By the way, so what can I do with that mask feature? I would like to see any example images or video what it does but found nothing on YT where anyone is using the mask. Just wanna know what it does and how the results looks like. Maybe you have any example images or video I could see it etc.

One word about the Enhance models. I did test them all with any single images and the only good one (more or less) are Enhance_GPEN & Enhance_CodeFormer models but none of both is really convincing. The GPEN has good sharpness but also much not detailed pixels artifacts and the teeth looking like Pennywise. On the other side the CodeFormer model is smooth and is showing good details (even good teeth without that horror look) but its also somehow blurry and sharpness is missing even contrast too. I would like to have a mix of GPEN & CodeFormer. So is it possible to create a custom model and change adjust values in the new model script? Or did anyone of you guys made already some custom model scripts I could test?

**Comment by gmf1982** [comment]
**I had the same problem:**
No CLI args supported - use Settings Tab instead
Using provider ['CUDAExecutionProvider'] - Device:cuda
D:\deepface\roop-unleashed\ui\tabs\faceswap_tab.py:54: GradioDeprecationWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  bt_srcfiles = gr.Files(label='Source File(s)', file_count="multiple", file_types=["image", ".fsz"], elem_id='filelist', height=233)
D:\deepface\roop-unleashed\ui\tabs\faceswap_tab.py:55: GradioDeprecationWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  bt_destfiles = gr.Files(label='Target File(s)', file_count="multiple", file_types=["image", "video"], elem_id='filelist', height=233)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Module roop.processors.Mask_Clip2Seg does not exist
Not using roop.processors.Mask_Clip2Seg
Traceback (most recent call last):
  File "D:\deepface\roop-unleashed\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\deepface\roop-unleashed\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\deepface\roop-unleashed\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\deepface\roop-unleashed\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\deepface\roop-unleashed\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\deepface\roop-unleashed\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\deepface\roop-unleashed\venv\lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "D:\deepface\roop-unleashed\ui\tabs\faceswap_tab.py", line 436, in on_preview_mask
    current_frame = preview_mask(current_frame, clip_text)
  File "D:\deepface\roop-unleashed\roop\core.py", line 206, in preview_mask
    return process_mgr.process_mask(maskprocessor, frame, maskimage)
  File "D:\deepface\roop-unleashed\roop\ProcessMgr.py", line 587, in process_mask
    img_mask = processor.Run(frame, self.options.masking_text)
AttributeError: 'NoneType' object has no attribute 'Run'

**Comment by Dean-Corso** [comment]
So you had & have still the same problem as me too @gmf1982 or did you found a solution? I can't use CUDA device if I don't have it and I can just use the CPU device only. Still could not find / fix this problem yet. 😞

**Comment by vpellegrain** [comment]
Hi @Dean-Corso and all,

I had the same problem and with some debugging I found the issue (at least on my computer). 
The problem came from importing dependencies in Mask_Clip2Seg.py, located in "roop/processors/Mask_Clip2Seg.py".

So i tried to manually import the package, which resulted in:

```
>>> import roop.processors.Mask_Clip2Seg.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/roop-unleashed/roop/processors/Mask_Clip2Seg.py", line 7, in <module>
    from clip.clipseg import CLIPDensePredT
  File "/roop-unleashed/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/roop-unleashed/clip/clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (unknown location)

```

I'm not very familiar with the `pkg_resources`, but after digging in my site-package folder, I saw that I have an independent packaging module. Thus, in the file `roop-unleashed/clip/clip.py` I changed the line 6:
`from pkg_resources import packaging`
into just:
`import packaging`

and I also commented the warning at lines 23 and 24:
```
#if packaging.version.parse(torch.__version__) < packaging.version.parse("1.7.1"):
#    warnings.warn("PyTorch version 1.7.1 or higher is recommended")
```

as it raised an issue.

Now it all works on my machine!

Hope this can help.

Cheers

**Comment by C0untFloyd** [comment]
Oh this is great, thanks @vpellegrain !
And as you probably noticed, the whole packaging version check isn't even needed because the requirement for roop unleashed is torch 2.1.2! About to test the version with it removed.

**Comment by C0untFloyd** [comment]
Ok, removed all of that and committed to test for you all. Can't wait to hear if it works for other people now too!
