### ISSUE TITLE
App fails to connect in Windows WinError 10054

### ISSUE THREAD

**Issue by jarrodmedrano** [C0untFloyd/roop-unleashed#466]
**Describe the bug**
app no longer runs

```
Launching App
Traceback (most recent call last):
  File "C:\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\roop-unleashed\installer\installer_files\env\lib\http\client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\roop-unleashed\installer\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\roop-unleashed\installer\installer_files\env\lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\roop-unleashed\installer\installer_files\env\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\roop-unleashed\installer\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "C:\roop-unleashed\installer\roop-unleashed\roop\core.py", line 355, in run
    if not pre_check():
  File "C:\roop-unleashed\installer\roop-unleashed\roop\core.py", line 120, in pre_check
    util.conditional_download(download_directory_path, ['https://huggingface.co/countfloyd/deepfake/resolve/main/inswapper_128.onnx'])
  File "C:\roop-unleashed\installer\roop-unleashed\roop\utilities.py", line 180, in conditional_download
    request = urllib.request.urlopen(url) # type: ignore[attr-defined]
  File "C:\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\roop-unleashed\installer\installer_files\env\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

```
**To Reproduce**
1. Installed from github, go to installer, run windows_run

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
latest
**Screenshots**

**Comment by elpatron975** [comment]
How we can resolve this problem ? I have the same issue

**Comment by jarrodmedrano** [comment]
> How we can resolve this problem ? I have the same issue
I went back to 3.0.2
Download an older version and do not update to latest version when you run installer.
