### ISSUE TITLE
google colab error

### ISSUE THREAD

**Issue by Kingkladzemcr** [C0untFloyd/roop-unleashed#493]
getting this on python run command

"Traceback (most recent call last):
  File "/content/roop-unleashed/roop-unleashed/run.py", line 6, in <module>
    core.run()
  File "/content/roop-unleashed/roop-unleashed/roop/core.py", line 359, in run
    if not pre_check():
  File "/content/roop-unleashed/roop-unleashed/roop/core.py", line 123, in pre_check
    util.conditional_download(download_directory_path, ['https://github.com/facefusion/facefusion-assets/releases/download/models/GPEN-BFR-512.onnx'])
  File "/content/roop-unleashed/roop-unleashed/roop/utilities.py", line 180, in conditional_download
    request = urllib.request.urlopen(url) # type: ignore[attr-defined]
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found"

**Comment by vl6** [comment]
!git clone https://github.com/C0untFloyd/roop-unleashed.git
%cd roop-unleashed
!git remote add pr-branch https://github.com/C0untFloyd/roop-unleashed.git
!git fetch pr-branch pull/494/head:pr-branch
!git checkout pr-branch
!mv config_colab.yaml config.yaml
!pip install pip install -r requirements.txt



Replace the middle cell with the above and it should work. You can use the normal version once the pr has been approved.
