### ISSUE TITLE
CUDA error: no kernel image available

### ISSUE THREAD

**Issue by ZTechGuy** [C0untFloyd/roop-unleashed#54]
**Describe the bug**
Unable to get roop-unleashed to run with GPU processing. When  I try to select a file, I receive the following error:

```
2023-07-20 18:42:46.6911522 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Resize node. Name:'Resize_124' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\roop_unleashed_win\installer_files\env\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\roop_unleashed_win\installer_files\env\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\roop_unleashed_win\roop-unleashed\roop\ui.py", line 66, in <lambda>
    source_button = ctk.CTkButton(root, text='Select image with face(s)', width=IMAGE_BUTTON_WIDTH, height=IMAGE_BUTTON_HEIGHT, compound='top', anchor='center', command=lambda: select_source_path())
  File "C:\roop_unleashed_win\roop-unleashed\roop\ui.py", line 164, in select_source_path
    INPUT_FACES_DATA = extract_face_images(roop.globals.source_path,  (False, 0))
  File "C:\roop_unleashed_win\roop-unleashed\roop\face_analyser.py", line 54, in extract_face_images
    faces = get_many_faces(source_image)
  File "C:\roop_unleashed_win\roop-unleashed\roop\face_analyser.py", line 35, in get_many_faces
    faces = get_face_analyser().get(frame)
  File "C:\roop_unleashed_win\installer_files\env\lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "C:\roop_unleashed_win\installer_files\env\lib\site-packages\insightface\model_zoo\retinaface.py", line 224, in detect
    scores_list, bboxes_list, kpss_list = self.forward(det_img, self.det_thresh)
  File "C:\roop_unleashed_win\installer_files\env\lib\site-packages\insightface\model_zoo\retinaface.py", line 152, in forward
    net_outs = self.session.run(self.output_names, {self.input_name : blob})
  File "C:\roop_unleashed_win\installer_files\env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Resize node. Name:'Resize_124' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
```
I'm relatively new to GPU computing, but I followed all of the steps as written and Google isn't helping much... What am I missing?

**To Reproduce**
1. Install with windows_run.bat, using the `--execution-provider cuda --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9` arguments
2. Click "Select image with face(s)"
3. See error

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Sanity Check**
- [X] I have the latest code from the github repository
- [X] I have followed the installation guide

**Comment by lysxelapsed** [comment]
seems like a stupid question, since you checked the installation guide box, but: are visual studio and cuda toolkit installed?
is it running without gpu-acceleration?

**Comment by ZTechGuy** [comment]
No worries, better safe than sorry!
I did install Visual Studio and the 11.8 Cuda toolkit specified in the [guide](https://github.com/s0md3v/roop/wiki/2.-Acceleration); I then ran installed dependencies as written too. The program is running as expected without GPU acceleration.

**Comment by phineas-pta** [comment]
what's ur gpu ?

**Comment by ZTechGuy** [comment]
It's an NVIDIA Quadro K620. Nothing too fancy, but it [looks like](https://developer.nvidia.com/cuda-gpus#:~:text=5.0-,quadro%20k620) it should be compatible with CUDA, if I'm understanding the attached page correctly.

**Comment by phineas-pta** [comment]
im afraid it's too old for AI framework
