### ISSUE TITLE
Error on Launching App

### ISSUE THREAD

**Issue by TapaNgumbara** [C0untFloyd/roop-unleashed#555]
```
Launching App
Using provider ['CPUExecutionProvider'] - Device:cpu
Traceback (most recent call last):
  File "D:\roop-unleashed-main\roop-unleashed-main\installer\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "D:\roop-unleashed-main\roop-unleashed-main\installer\roop-unleashed\roop\core.py", line 367, in run
    main.run()
  File "D:\roop-unleashed-main\roop-unleashed-main\installer\roop-unleashed\ui\main.py", line 56, in run
    if server_port <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```
Windows 11
AMD Ryzen 7 5700G
GPU (integrated Radeon™ Graphics)

**Comment by JayJackRussel** [comment]
You are using Python 3.9 or older.
You should update your Python to 3.10 or newer.

**Comment by TapaNgumbara** [comment]
> You are using Python 3.9 or older. You should update your Python to 3.10 or newer.
Python 3.12

**Comment by TapaNgumbara** [comment]
> You are using Python 3.9 or older. You should update your Python to 3.10 or newer.

Python 3.12

**Comment by C0untFloyd** [comment]
Corrupted config file? You should have a file in your roop folder looking like the one I attached here. The extension really is .yaml but Github didn't like that so I changed it to .txt here.

[config.txt](https://github.com/C0untFloyd/roop-unleashed/files/14769972/config.txt)

**Comment by TapaNgumbara** [comment]
> Corrupted config file? You should have a file in your roop folder looking like the one I attached here. The extension really is .yaml but Github didn't like that so I changed it to .txt here.
> 
> [config.txt](https://github.com/C0untFloyd/roop-unleashed/files/14769972/config.txt)

Thank you very much for your help, I got it now. :) thanks
