### ISSUE TITLE
Both videos and faces uploaded result in "........ is not in the upload folder and cannot be accessed"

### ISSUE THREAD

**Issue by MantisTree** [C0untFloyd/roop-unleashed#560]
Roop-unleashed has been working fine for months. Many updates have been successful, but today I updated to the latest and am getting errors.  I closed and restarted the session/program to make sure it wasn't a fluke.  Here is an entire session:

Thanks for any help!

```
Launching roop unleashed - please edit windows_run.bat to customize commandline arguments
Check for Updates? [y/n]y
HEAD is now at 9907f1f Bugfix: Removed packaging from clip which caused issues for some people Reverted back to numpy 1.24.3 due to install problems
Already up to date.
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring onnxruntime: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Requirement already satisfied: numpy==1.24.3 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 3)) (1.24.3)
Requirement already satisfied: gradio==4.21.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 4)) (4.21.0)
Requirement already satisfied: opencv-python==4.8.1.78 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 5)) (4.8.1.78)
Requirement already satisfied: onnx==1.15.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 6)) (1.15.0)
Requirement already satisfied: insightface==0.7.3 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 7)) (0.7.3)
Requirement already satisfied: psutil==5.9.6 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 8)) (5.9.6)
Requirement already satisfied: torch==2.1.2+cu118 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 9)) (2.1.2+cu118)
Requirement already satisfied: torchvision==0.16.2+cu118 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 11)) (0.16.2+cu118)
Requirement already satisfied: onnxruntime-gpu==1.16.3 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 15)) (1.16.3)
Requirement already satisfied: tqdm==4.66.2 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 16)) (4.66.2)
Requirement already satisfied: ftfy in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 17)) (6.1.1)
Requirement already satisfied: regex in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 18)) (2023.8.8)
Requirement already satisfied: pyvirtualcam in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from -r requirements.txt (line 19)) (0.10.2)
Requirement already satisfied: aiofiles<24.0,>=22.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (23.2.1)
Requirement already satisfied: altair<6.0,>=4.2.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (5.1.1)
Requirement already satisfied: fastapi in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.103.1)
Requirement already satisfied: ffmpy in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.3.1)
Requirement already satisfied: gradio-client==0.12.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.12.0)
Requirement already satisfied: httpx>=0.24.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.25.0)
Requirement already satisfied: huggingface-hub>=0.19.3 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.22.2)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (6.1.0)
Requirement already satisfied: jinja2<4.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (3.1.2)
Requirement already satisfied: markupsafe~=2.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (2.1.3)
Requirement already satisfied: matplotlib~=3.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (3.8.0)
Requirement already satisfied: orjson~=3.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (3.9.7)
Requirement already satisfied: packaging in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (23.1)
Requirement already satisfied: pandas<3.0,>=1.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (2.1.1)
Requirement already satisfied: pillow<11.0,>=8.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (10.0.1)
Requirement already satisfied: pydantic>=2.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (2.4.1)
Requirement already satisfied: pydub in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.9 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.0.9)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (6.0.1)
Requirement already satisfied: ruff>=0.2.2 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.3.4)
Requirement already satisfied: semantic-version~=2.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (2.10.0)
Requirement already satisfied: tomlkit==0.12.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.12.0)
Requirement already satisfied: typer[all]<1.0,>=0.9 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.11.1)
Requirement already satisfied: typing-extensions~=4.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (4.8.0)
Requirement already satisfied: uvicorn>=0.14.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio==4.21.0->-r requirements.txt (line 4)) (0.23.2)
Requirement already satisfied: protobuf>=3.20.2 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from onnx==1.15.0->-r requirements.txt (line 6)) (4.23.2)
Requirement already satisfied: requests in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (2.31.0)
Requirement already satisfied: scipy in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (1.11.2)
Requirement already satisfied: scikit-learn in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: scikit-image in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (0.21.0)
Requirement already satisfied: easydict in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (1.10)
Requirement already satisfied: cython in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (3.0.2)
Requirement already satisfied: albumentations in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: prettytable in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from insightface==0.7.3->-r requirements.txt (line 7)) (3.9.0)
Requirement already satisfied: filelock in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from torch==2.1.2+cu118->-r requirements.txt (line 9)) (3.12.4)
Requirement already satisfied: sympy in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from torch==2.1.2+cu118->-r requirements.txt (line 9)) (1.12)
Requirement already satisfied: networkx in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from torch==2.1.2+cu118->-r requirements.txt (line 9)) (3.1)
Requirement already satisfied: fsspec in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from torch==2.1.2+cu118->-r requirements.txt (line 9)) (2023.9.2)
Requirement already satisfied: coloredlogs in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from onnxruntime-gpu==1.16.3->-r requirements.txt (line 15)) (15.0.1)
Requirement already satisfied: flatbuffers in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from onnxruntime-gpu==1.16.3->-r requirements.txt (line 15)) (23.5.26)
Requirement already satisfied: colorama in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from tqdm==4.66.2->-r requirements.txt (line 16)) (0.4.6)
Requirement already satisfied: websockets<12.0,>=10.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from gradio-client==0.12.0->gradio==4.21.0->-r requirements.txt (line 4)) (11.0.3)
Requirement already satisfied: wcwidth>=0.2.5 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from ftfy->-r requirements.txt (line 17)) (0.2.6)
Requirement already satisfied: jsonschema>=3.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from altair<6.0,>=4.2.0->gradio==4.21.0->-r requirements.txt (line 4)) (4.19.1)
Requirement already satisfied: toolz in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from altair<6.0,>=4.2.0->gradio==4.21.0->-r requirements.txt (line 4)) (0.12.0)
Requirement already satisfied: certifi in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from httpx>=0.24.1->gradio==4.21.0->-r requirements.txt (line 4)) (2023.7.22)
Requirement already satisfied: httpcore<0.19.0,>=0.18.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from httpx>=0.24.1->gradio==4.21.0->-r requirements.txt (line 4)) (0.18.0)
Requirement already satisfied: idna in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from httpx>=0.24.1->gradio==4.21.0->-r requirements.txt (line 4)) (3.4)
Requirement already satisfied: sniffio in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from httpx>=0.24.1->gradio==4.21.0->-r requirements.txt (line 4)) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib~=3.0->gradio==4.21.0->-r requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib~=3.0->gradio==4.21.0->-r requirements.txt (line 4)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib~=3.0->gradio==4.21.0->-r requirements.txt (line 4)) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib~=3.0->gradio==4.21.0->-r requirements.txt (line 4)) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib~=3.0->gradio==4.21.0->-r requirements.txt (line 4)) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from matplotlib~=3.0->gradio==4.21.0->-r requirements.txt (line 4)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from pandas<3.0,>=1.0->gradio==4.21.0->-r requirements.txt (line 4)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from pandas<3.0,>=1.0->gradio==4.21.0->-r requirements.txt (line 4)) (2023.3)
Requirement already satisfied: annotated-types>=0.4.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from pydantic>=2.0->gradio==4.21.0->-r requirements.txt (line 4)) (0.5.0)
Requirement already satisfied: pydantic-core==2.10.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from pydantic>=2.0->gradio==4.21.0->-r requirements.txt (line 4)) (2.10.1)
Requirement already satisfied: click>=8.0.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from typer[all]<1.0,>=0.9->gradio==4.21.0->-r requirements.txt (line 4)) (8.1.7)
Requirement already satisfied: shellingham<2.0.0,>=1.3.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from typer[all]<1.0,>=0.9->gradio==4.21.0->-r requirements.txt (line 4)) (1.5.4)
Requirement already satisfied: rich<14.0.0,>=10.11.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from typer[all]<1.0,>=0.9->gradio==4.21.0->-r requirements.txt (line 4)) (13.7.1)
Requirement already satisfied: h11>=0.8 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from uvicorn>=0.14.0->gradio==4.21.0->-r requirements.txt (line 4)) (0.14.0)
Requirement already satisfied: qudida>=0.0.4 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3->-r requirements.txt (line 7)) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from albumentations->insightface==0.7.3->-r requirements.txt (line 7)) (4.8.0.76)
Requirement already satisfied: imageio>=2.27 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (2.31.4)
Requirement already satisfied: tifffile>=2022.8.12 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (2023.9.26)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (1.4.1)
Requirement already satisfied: lazy_loader>=0.2 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-image->insightface==0.7.3->-r requirements.txt (line 7)) (0.3)
Requirement already satisfied: humanfriendly>=9.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from coloredlogs->onnxruntime-gpu==1.16.3->-r requirements.txt (line 15)) (10.0)
Requirement already satisfied: anyio<4.0.0,>=3.7.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from fastapi->gradio==4.21.0->-r requirements.txt (line 4)) (3.7.1)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from fastapi->gradio==4.21.0->-r requirements.txt (line 4)) (0.27.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (3.2.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from requests->insightface==0.7.3->-r requirements.txt (line 7)) (2.0.5)
Requirement already satisfied: joblib>=1.1.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-learn->insightface==0.7.3->-r requirements.txt (line 7)) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from scikit-learn->insightface==0.7.3->-r requirements.txt (line 7)) (3.2.0)
Requirement already satisfied: mpmath>=0.19 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from sympy->torch==2.1.2+cu118->-r requirements.txt (line 9)) (1.3.0)
Requirement already satisfied: exceptiongroup in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from anyio<4.0.0,>=3.7.1->fastapi->gradio==4.21.0->-r requirements.txt (line 4)) (1.1.3)
Requirement already satisfied: pyreadline3 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu==1.16.3->-r requirements.txt (line 15)) (3.4.1)
Requirement already satisfied: attrs>=22.2.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==4.21.0->-r requirements.txt (line 4)) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==4.21.0->-r requirements.txt (line 4)) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==4.21.0->-r requirements.txt (line 4)) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio==4.21.0->-r requirements.txt (line 4)) (0.10.3)
Requirement already satisfied: six>=1.5 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from python-dateutil>=2.7->matplotlib~=3.0->gradio==4.21.0->-r requirements.txt (line 4)) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from rich<14.0.0,>=10.11.0->typer[all]<1.0,>=0.9->gradio==4.21.0->-r requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from rich<14.0.0,>=10.11.0->typer[all]<1.0,>=0.9->gradio==4.21.0->-r requirements.txt (line 4)) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in c:\roop-unleashed\installer\installer_files\env\lib\site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=10.11.0->typer[all]<1.0,>=0.9->gradio==4.21.0->-r requirements.txt (line 4)) (0.1.2)
Launching App
Using provider ['CUDAExecutionProvider'] - Device:cuda
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1686, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1391, in preprocess_data
    inputs_cached = processing_utils.move_files_to_cache(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\processing_utils.py", line 303, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio_client\utils.py", line 1015, in traverse
    new_obj.append(traverse(item, func, is_root))
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio_client\utils.py", line 1006, in traverse
    return func(json_obj)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\processing_utils.py", line 276, in _move_to_cache
    raise ValueError(
ValueError: File C:\Users\Generic Human\AppData\Local\Temp\4780a4005c0cd86c3d76d23243d1b81d5573b0d9\the.rockford.files.s05e19.dvdrip.xvid.sample-nodlabs.avi is not in the upload folder and cannot be accessed.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "c:\roop-unleashed\installer\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\roop-unleashed\installer\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1686, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1391, in preprocess_data
    inputs_cached = processing_utils.move_files_to_cache(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\processing_utils.py", line 303, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio_client\utils.py", line 1015, in traverse
    new_obj.append(traverse(item, func, is_root))
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio_client\utils.py", line 1006, in traverse
    return func(json_obj)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\processing_utils.py", line 276, in _move_to_cache
    raise ValueError(
ValueError: File C:\Users\Generic Human\AppData\Local\Temp\4780a4005c0cd86c3d76d23243d1b81d5573b0d9\the.rockford.files.s05e19.dvdrip.xvid.sample-nodlabs.avi is not in the upload folder and cannot be accessed.
Traceback (most recent call last):
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1686, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1391, in preprocess_data
    inputs_cached = processing_utils.move_files_to_cache(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\processing_utils.py", line 303, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio_client\utils.py", line 1015, in traverse
    new_obj.append(traverse(item, func, is_root))
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio_client\utils.py", line 1006, in traverse
    return func(json_obj)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\processing_utils.py", line 276, in _move_to_cache
    raise ValueError(
ValueError: File C:\Users\Generic Human\AppData\Local\Temp\1da426dca46c3e7a77bedc44604e521bafa261f3\scottface.png is not in the upload folder and cannot be accessed.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "c:\roop-unleashed\installer\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\roop-unleashed\installer\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by Roosh12** [comment]
it's the same happening with me except that it's my first time of use

**Comment by C0untFloyd** [comment]
You could try using the temp folder from the app as your one contains spaces (don't know if that can be an issue with gradio).
For everything else see #564

**Comment by MantisTree** [comment]
> You could try using the temp folder from the app as your one contains spaces (don't know if that can be an issue with gradio). For everything else see #564

Can confirm, setting the temp folder to  folder with no space before invoking the program remediated the error. 

`SET TEMP=C:\TEMP
SET TMP=C:\TEMP`
