### ISSUE TITLE
Gradio Update Error

### ISSUE THREAD

**Issue by poepoeng** [C0untFloyd/roop-unleashed#562]
**Describe the bug**
I think gradio make update again, i run python on 3.10 and 3.9 has same error. Try to reinstall typer didnt help.

**To Reproduce**
1. Go to 'python run.py'
2. See error

`Traceback (most recent call last):
  File "/notebooks/roop-unleashed/run.py", line 3, in <module>
    from roop import core
  File "/notebooks/roop-unleashed/roop/core.py", line 22, in <module>
    import roop.utilities as util
  File "/notebooks/roop-unleashed/roop/utilities.py", line 11, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 10, in <module>
    from gradio.cli import deploy
  File "/usr/local/lib/python3.10/dist-packages/gradio/cli/__init__.py", line 1, in <module>
    from .cli import cli, deploy
  File "/usr/local/lib/python3.10/dist-packages/gradio/cli/cli.py", line 4, in <module>
    from gradio_client.cli import deploy_discord  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/gradio_client/cli/__init__.py", line 1, in <module>
    from gradio_client.cli import deploy_discord
  File "/usr/local/lib/python3.10/dist-packages/gradio_client/cli/deploy_discord.py", line 3, in <module>
    from typer import Option
ImportError: cannot import name 'Option' from 'typer' (unknown location)`

**Details**
What OS are you using?
- [ x ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ x ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.6.5

**Screenshots**

Thank you

**Comment by C0untFloyd** [comment]
#564

**Comment by poepoeng** [comment]
im trying to downgrade typer to 0.11 and its work. thanks
