### ISSUE TITLE
broken command line

### ISSUE THREAD

**Issue by illtellyoulater** [C0untFloyd/roop-unleashed#6]
**Describe the bug**
Running from the command line, in the original fork everything works correctly, while in this one I'm getting errors.
In one of the error lines (full log below) the UI is referenced:
```
frame_processor.process_video(ui.SELECTED_FACE_DATA_INPUT, ui.SELECTED_FACE_DATA_OUTPUT, temp_frame_paths)
```
Could this be responsible for the error?

**To Reproduce**
Just run:
```
python3 run.py --source ~/Pictures/input-pic.jpg --target ~/Videos/input-vid.mp4 -o ~/Videos/output.mp4 --frame-processor face_swapper face_enhancer --keep-audio --execution-provider cuda --execution-threads 3
```

Output:
```
Processing:   0%|                                                       | 0/1773 [00:01<?, ?frame/s]
Traceback (most recent call last):
  File "/home/testing/Apps-testing/roop-faceswapper/roop-unleashed/run.py", line 6, in <module>
    core.run()
  File "/home/testing/Apps-testing/roop-faceswapper/roop-unleashed/roop/core.py", line 224, in run
    start()
  File "/home/testing/Apps-testing/roop-faceswapper/roop-unleashed/roop/core.py", line 180, in start
    frame_processor.process_video(ui.SELECTED_FACE_DATA_INPUT, ui.SELECTED_FACE_DATA_OUTPUT, temp_frame_paths)
  File "/home/testing/Apps-testing/roop-faceswapper/roop-unleashed/roop/processors/frame/face_swapper.py", line 111, in process_video
    roop.processors.frame.core.process_video(source_face, target_face, temp_frame_paths, process_frames)
  File "/home/testing/Apps-testing/roop-faceswapper/roop-unleashed/roop/processors/frame/core.py", line 81, in process_video
    multi_process_frame(source_face, target_face, frame_paths, process_frames, lambda: update_progress(progress))
  File "/home/testing/Apps-testing/roop-faceswapper/roop-unleashed/roop/processors/frame/core.py", line 59, in multi_process_frame
    future.result()
  File "/opt/conda/envs/roop/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/conda/envs/roop/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/conda/envs/roop/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/testing/Apps-testing/roop-faceswapper/roop-unleashed/roop/processors/frame/face_swapper.py", line 92, in process_frames
    result = process_frame(source_face, target_face, temp_frame)
  File "/home/testing/Apps-testing/roop-faceswapper/roop-unleashed/roop/processors/frame/face_swapper.py", line 84, in process_frame
    temp_frame = swap_face(source_face, target_face, temp_frame)
  File "/home/testing/Apps-testing/roop-faceswapper/roop-unleashed/roop/processors/frame/face_swapper.py", line 56, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "/opt/conda/envs/roop/lib/python3.10/site-packages/insightface/model_zoo/inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'normed_embedding'
```

**Details**
What OS are you using?
- [ x ] Linux

Are you try to use a GPU?
- [ x ] NVIDIA

**Sanity Check**
- [ x ] I have the latest code from the github repository
- [ x ] I have followed the installation guide

**Comment by C0untFloyd** [comment]
I neglected the CLI stuff but with the latest v2.0.0 this should work again.
