### ISSUE TITLE
roop urllib.error.URLError

### ISSUE THREAD

**Issue by simpleness23** [C0untFloyd/roop-unleashed#607]
**Describe the bug**
After I install roop and try to run the installer I receive the following error:

Traceback (most recent call last):
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\http\client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\Documents\roop-unleashed-main\installer\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "C:\Users\me\Documents\roop-unleashed-main\installer\roop-unleashed\roop\core.py", line 360, in run
    if not pre_check():
  File "C:\Users\me\Documents\roop-unleashed-main\installer\roop-unleashed\roop\core.py", line 120, in pre_check
    util.conditional_download(download_directory_path, ['https://huggingface.co/countfloyd/deepfake/resolve/main/inswapper_128.onnx'])
  File "C:\Users\me\Documents\roop-unleashed-main\installer\roop-unleashed\roop\utilities.py", line 196, in conditional_download
    request = urllib.request.urlopen(url)  # type: ignore[attr-defined]
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\me\Documents\roop-unleashed-main\installer\installer_files\env\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

I am having the same bug as this user: https://github.com/C0untFloyd/roop-unleashed/issues/587

Steps to try to resolve:
1. Installed the latest version of roop
2. Change my DNS settings to public query 8.8.8.8 and 8.8.4.4
3. Turned off Windows Defender
4. Manually downloaded and placed models in the correct folder
5. Updated and restarted my computer
6. Used checked for updates
7. Attempted to run on Google Chrome, Microsoft Edge, and Mozilla Firefox.

**Details**
OS
- [11] Windows 

Are you using a GPU?
- No. CPU 

**Which version of roop unleashed are you using?**
Latest version posted 4 days ago.

**Comment by simpleness23** [comment]
Resolved the issue by installing on a different network.
