### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape

### ISSUE THREAD

**Issue by hashik4d** [C0untFloyd/roop-unleashed#61]
**Describe the bug**

When you try to run from CLI using the below commands 

PS D:\OneDrive\Desktop\HashikADOProject\roop-unleashed> **python run.py  --source "D:\OneDrive\DeepFaceLab\rCH.jpg" --target "D:\OneDrive\DeepFaceLab\target2.mp4" --output "D:\OneDrive\DeepFaceLab\Rachfinal.mp4"  --source-face_index 0 --target-face_index 0   --video-quality 18  --execution-provider cuda**

It Throws the below error message. But when just use > **python run.py  --execution-provider cuda** Everything works in the UI. 
```
Loading roop.processors.frame.face_swapper
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\hashi/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\hashi/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\hashi/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\hashi/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\hashi/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Traceback (most recent call last):
  File "D:\OneDrive\Desktop\HashikADOProject\roop-unleashed\run.py", line 6, in <module>
    core.run()
  File "D:\OneDrive\Desktop\HashikADOProject\roop-unleashed\roop\core.py", line 308, in run
    start()
  File "D:\OneDrive\Desktop\HashikADOProject\roop-unleashed\roop\core.py", line 155, in start
    faces = extract_face_images(roop.globals.target_path,  (False, has_image_extension(roop.globals.target_path)))
  File "D:\OneDrive\Desktop\HashikADOProject\roop-unleashed\roop\face_analyser.py", line 54, in extract_face_images
    faces = get_many_faces(source_image)
  File "D:\OneDrive\Desktop\HashikADOProject\roop-unleashed\roop\face_analyser.py", line 35, in get_many_faces
    faces = get_face_analyser().get(frame)
  File "C:\Users\hashi\AppData\Local\Programs\Python\Python39\lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "C:\Users\hashi\AppData\Local\Programs\Python\Python39\lib\site-packages\insightface\model_zoo\retinaface.py", line 211, in detect
    im_ratio = float(img.shape[0]) / img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape

```
**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [X ] Windows 
- [ ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ X] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [ X] I have the latest code from the github repository
- [X ] I have followed the installation guide

**Comment by C0untFloyd** [comment]
Closed all old issues because of new rewritten version.
