### ISSUE TITLE
LiveCam error when I select input image

### ISSUE THREAD

**Issue by kbecla** [C0untFloyd/roop-unleashed#630]
Hello and thank you in advance in addition to your effort on this project.

I am having an issue when I enable the live cam feature.   I am able to get an image in the browser and I can stream in OBS but the moment I specify an input image I get this error in the command prompt:

Exception in thread Thread-8 (virtualcamera):
Traceback (most recent call last):
  File "C:\Tutorial\roop-unleashed-main30\roop-unleashed-main\installer\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Tutorial\roop-unleashed-main30\roop-unleashed-main\installer\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Tutorial\roop-unleashed-main30\roop-unleashed-main\installer\roop-unleashed\roop\virtualcam.py", line 57, in virtualcamera
    frame = live_swap(frame, "all", options)
TypeError: live_swap() takes 2 positional arguments but 3 were given

**Comment by C0untFloyd** [comment]
Oh you found a bug in the new version! For the moment you could fix it yourself by removing the "all" parameter so the line looks like:
`frame = live_swap(frame,  options)`
Thanks for the info, I'm hoping to find some time tomorrow to repair this in the repo.
