### ISSUE TITLE
Clip2Seg broken

### ISSUE THREAD

**Issue by MantisTree** [C0untFloyd/roop-unleashed#632]
Long-time user of roop-unleashed, long-time user of Clip2Seg. 

After latest update, any attempt to use Clip2Seg or Show Mask Preview for Clip2Seg results in "Error"

Console output:

```Traceback (most recent call last):
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "c:\roop-unleashed\installer\roop-unleashed\ui\tabs\faceswap_tab.py", line 543, in on_preview_mask
    current_frame = live_swap(current_frame, options)
  File "c:\roop-unleashed\installer\roop-unleashed\roop\core.py", line 193, in live_swap
    process_mgr.initialize(roop.globals.INPUT_FACESETS, roop.globals.TARGET_FACES, options)
  File "c:\roop-unleashed\installer\roop-unleashed\roop\ProcessMgr.py", line 109, in initialize
    classname = self.plugins[pn]
KeyError: 'Clip2Seg'
Traceback (most recent call last):
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "c:\roop-unleashed\installer\roop-unleashed\ui\tabs\faceswap_tab.py", line 543, in on_preview_mask
    current_frame = live_swap(current_frame, options)
  File "c:\roop-unleashed\installer\roop-unleashed\roop\core.py", line 193, in live_swap
    process_mgr.initialize(roop.globals.INPUT_FACESETS, roop.globals.TARGET_FACES, options)
  File "c:\roop-unleashed\installer\roop-unleashed\roop\ProcessMgr.py", line 109, in initialize
    classname = self.plugins[pn]
KeyError: 'Clip2Seg'
```

Thanks!

**Comment by C0untFloyd** [comment]
Yes, 1 small little typo!
Fixed in https://github.com/C0untFloyd/roop-unleashed/commit/7c75de68456fefd62a7ae85ce529b023acac44cf
