### ISSUE TITLE
roop unleashed Gradio - WIP Thread

### ISSUE THREAD

**Issue by C0untFloyd** [C0untFloyd/roop-unleashed#64]
For the brave and adventurous among you, I just made the gradio branch public.

I think you're in for a treat because this has several cool new additions, to name just a few:

* Drag'n Drop Support of Images/Files
* Scrubbing through videos to select faces from frames or just preview the deepfake with current settings
* Clipseg masking to restore stuff from the original image
* Live Fake Webcam (select your new face in the tab before)
* Lots of sliders for the dynamic settings like blend ratio
* Proper GIF Support
* Faster processing through memory processing, no temp file writing anymore

Be aware that there is still lots of work to be done, some stuff might break, it's in no way optimized or clean code. However in the future the gradio version will replace the main branch. Before that happens I will create another small QoL and bugfixed version of the TkInter Version (without the new stuff), just in case people want to continue using that one for dubious reasons.

To checkout:
`git clone -b gradio --single-branch https://github.com/C0untFloyd/roop-unleashed.git`
`cd roop-unleashed`
`conda create -n mynewshinyroop`
`conda activate mynewshinyroop`
`pip install -r requirements.txt`

Run it with the same parameters as previously e.g. `python run.py --execution-provider cuda --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9`

Please limit posts about this version to this thread only, thank you!

**Comment by RealCalumPlays** [comment]
Live camera doesnt work. Heres the traceback:

`Traceback (most recent call last):
  File "C:\Users\Calum\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Calum\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "C:\Users\Calum\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\gradio\blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Calum\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Calum\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Calum\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Calum\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Calum\Documents\roop-unleashed\roop\ui.py", line 497, in on_stream_swap_cam
    current_cam_image = live_swap(camimage, "all")
TypeError: live_swap() missing 2 required positional arguments: 'use_clip' and 'clip_text'`

**Comment by C0untFloyd** [comment]
Thanks, was missing the last minute clip parameters. Fixed now, please do a git pull.

**Comment by tfis2** [comment]
First:
Thank you very much for your work!!!
It's great that you can drag and drop files, even *.png with multiple faces.

Clip Masking leads to an error:

Traceback (most recent call last):
  File "C:\Users\info\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\info\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "C:\Users\info\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\info\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\info\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\info\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\info\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "D:\StableDiffusion\roopunl\beta\roop-unleashed\roop\ui.py", line 448, in start_preview
    current_frame = live_swap(current_frame, roop.globals.face_swap_mode, use_clip, clip_text)
  File "D:\StableDiffusion\roopunl\beta\roop-unleashed\roop\core.py", line 202, in live_swap
    temp_frame, _ = roop.globals.IMAGE_CHAIN_PROCESSOR.run_chain(frame,
  File "D:\StableDiffusion\roopunl\beta\roop-unleashed\chain_img_processor\image.py", line 85, in run_chain
    img = self.processors_objects[proc_id][thread_index].process(img,params)
KeyError: 'txt2clip'

---

When scrubbing "Preview face swap" is off. Only works with original face.

**Comment by jmp909** [comment]
some quick observations (Windows 11, RTX 3080)

* when doing a batch image convert of say 400 images with codeformer, the termianl output stops at 8/400 images (maybe related to 8 execution threads?) for the rest of the process, and never updates past that even though the swapping process is continuing in the background 

* for images would be useful to allow either eg "Keep original file format" or an option for the save file type. My 100K JPGs are being re-saved as swapped 2MB PNG's, but JPG would be fine and smaller.

thanks

**Comment by TrickleDownClown** [comment]
Awesome.  I'm looking forward to trying it.  I'll report back tomorrow.

**Comment by maxbizz** [comment]
this is the error its throwing btw im using venv instead of conda
 "Traceback (most recent call last):
  File "G:\Github\roop\venv\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Github\roop\venv\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "G:\Github\roop\venv\lib\site-packages\gradio\blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Github\roop\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Github\roop\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Github\roop\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Github\roop\venv\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "G:\Github\roop\roop\ui.py", line 419, in start_swap
    batch_process([file.name for file in target_files], use_clip, clip_text)
  File "G:\Github\roop\roop\core.py", line 266, in batch_process
    roop.globals.BATCH_IMAGE_CHAIN_PROCESSOR.run_batch_chain(imagefiles, imagefinalnames, 8, processors, params_gen_func)
  File "G:\Github\roop\chain_img_processor\batchimage.py", line 85, in run_batch_chain
    future.result()
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "G:\Github\roop\chain_img_processor\batchimage.py", line 62, in process_frames
    resimg, _ = self.run_chain(temp_frame, params, self.chain)
  File "G:\Github\roop\chain_img_processor\image.py", line 85, in run_chain
    img = self.processors_objects[proc_id][thread_index].process(img,params)
  File "G:\Github\roop\plugins\plugin_faceswap.py", line 47, in process
    frame = swap_face(params["input_face_datas"][0], face, frame)
  File "G:\Github\roop\roop\face_helper.py", line 90, in swap_face
    return get_face_swapper().get(temp_frame, target_face, source_face, paste_back=True)
  File "G:\Github\roop\venv\lib\site-packages\insightface\model_zoo\inswapper.py", line 50, in get
    latent = source_face.normed_embedding.reshape((1,-1))
AttributeError: 'NoneType' object has no attribute 'normed_embedding'
Traceback (most recent call last):
  File "G:\Github\roop\venv\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Github\roop\venv\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "G:\Github\roop\venv\lib\site-packages\gradio\blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Github\roop\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Github\roop\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Github\roop\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Github\roop\venv\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "G:\Github\roop\roop\ui.py", line 274, in remove_selected_input_face
    if len(input_thumbs) > SELECTED_INPUT_FACE_INDEX:
NameError: name 'SELECTED_INPUT_FACE_INDEX' is not defined
"

**Comment by C0untFloyd** [comment]
>when doing a batch image convert of say 400 images, the terminal output stops at 8/400 images
>or images would be useful to allow either eg "Keep original file format" or an option for the save file type. 
>NameError: name 'SELECTED_INPUT_FACE_INDEX' is not defined
>KeyError: 'txt2clip'

Fixed or added in the latest update.

> When scrubbing "Preview face swap" is off. Only works with original face.

It's meant to position the video to a frame you want to check out. Live-swapping with all options turned on is way too slow (at least on my system).

> would help if Target file(s) list was a fixed-height scrollable list because currently it stretches out the whle UI vertically with a lot of files - making it harder to get to eg "Use face from this frame"

Of course! I'd like this for every multifile box but this is currently supported by gradio. I'm trying to hack this in with CSS/HTML trickery like automatic1111 did with a lot of components but without luck so far. I also had bugs with lots of input files, there seems to be a magic limit of ~400 input files.
