### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by aximili** [C0untFloyd/roop-unleashed#704]
**Describe the bug**
After clicking Start, a few seconds later it fails with this error:

> Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\roop-unleashed-main\installer\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\roop-unleashed-main\installer\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**To Reproduce**
1. Download ffmpeg into `C:\ffmpeg` and put `C:\ffmpeg\bin` into env variable (Path)
2. Download roop-unleashed-main.zip and extract to E:\
3. Run `E:\roop-unleashed-main\installer\windows_run.bat`, which opens http://127.0.0.1:7860/ in the browser
4. Drag a single image containing a single face into Source File(s)
5. Drag a single small video into Target File(s)
6. Click Start
7. The error happens, while the seemingly-unedited video is displayed in the Final Video panel

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 11
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA (RTX 4060 Ti)
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
3.9.0

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1844817/30bcb4bd-ebe1-4def-be6d-376b4d906eef)

**More details**
The first time I ran Roop Unleashed, it complained about ffmpeg not installed. I had to install it manually and added it to env variable. I then had to uninstall/reinstall Roop Unleashed and restart the PC.

IIRC I also deleted some env variables that pointed to the `roop-unleashed-main` folder when I tried uninstalling Roop Unleashed. But now I can't see any env variables pointing to the `roop-unleashed-main` folder anymore.

Please let me know what I can do to fix the error. Thank you.

**Comment by aximili** [comment]
Solved. I reinstalled by uninstalling ffmpeg, then reinstalled, then reinstalled ffmpeg, then restarted PC. Now it can replace faces, although the error is still there but I don't care as long as it does what it needs to do.
