### ISSUE TITLE
Issue after cleaning temp folder and restart: roop continue to use old files from the old generation

### ISSUE THREAD

**Issue by mammuthus** [C0untFloyd/roop-unleashed#776]
**Describe the bug**
After cleaning the temp folder (with 'Clean temp folder' button) and restarting the server (with 'Restart Server' button), Roop has become broken. It shows the error "No such file or directory: 'C:\\roop-unleashed\\roop-unleashed\\temp\\95cb2d7c3ed893ad6ee591568e2ac8dd87e5d1bd\\vita.jpg'", even though **vita.jpg** is not part of the current generation. I only have two files loaded: **man.jpg** and **man2.jpg**; there's nothing involving **vita.jpg**. 
**vita.jpg** source file was used in previous generations, before I cleared the temp folder and restarted the server.

Restarting the server doesn't help. 'Clear all' clears the current Input set as expected, but has no effect on the issue.
Seems like the 'Clean temp folder' works not as expected.

How can I get Roop back to work?

CLI error:
```
Closing server running on port: 7860
Running on local URL:  http://127.0.0.1:7860
INFO:httpx:HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
Sorting videos/images
Processing image(s)
Processing:  80%|███████████████████████▏     | 4/5 [00:03<00:00,  1.02frame/s, memory_usage=01.63GB, execution_threads=6]
Traceback (most recent call last):
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\gradio\queueing.py", line 560, in process_events
    response = await route_utils.call_process_api(
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\gradio\blocks.py", line 1525, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 655, in async_iteration
    return await iterator.__anext__()
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 648, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 631, in run_sync_iterator_async
    return next(iterator)
  File "C:\roop-unleashed\installer_files\env\lib\site-packages\gradio\utils.py", line 814, in gen_wrapper
    response = next(iterator)
  File "C:\roop-unleashed\roop-unleashed\ui\tabs\faceswap_tab.py", line 621, in start_swap
    batch_process_regular(list_files_process, mask_engine, clip_text, processing_method == "In-Memory processing", imagemask, num_swap_steps, progress, SELECTED_INPUT_FACE_INDEX)
  File "C:\roop-unleashed\roop-unleashed\roop\core.py", line 219, in batch_process_regular
    batch_process(files, use_new_method)
  File "C:\roop-unleashed\roop-unleashed\roop\core.py", line 277, in batch_process
    process_mgr.run_batch(origimages, fakeimages, roop.globals.execution_threads)
  File "C:\roop-unleashed\roop-unleashed\roop\ProcessMgr.py", line 169, in run_batch
    future.result()
  File "C:\roop-unleashed\installer_files\env\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\roop-unleashed\installer_files\env\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\roop-unleashed\installer_files\env\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\roop-unleashed\roop-unleashed\roop\ProcessMgr.py", line 178, in process_frames
    temp_frame = cv2.imdecode(np.fromfile(f, dtype=np.uint8), cv2.IMREAD_COLOR)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\roop-unleashed\\roop-unleashed\\temp\\95cb2d7c3ed893ad6ee591568e2ac8dd87e5d1bd\\vita.jpg'
```

GUI error:
```
[Errno 2] No such file or directory: 'C:\\roop-unleashed\\roop-unleashed\\temp\\95cb2d7c3ed893ad6ee591568e2ac8dd87e5d1bd\\vita.jpg'
```

**To Reproduce**
1. Generate face swap
2. Click on 'Clean temp folder' button
3. Click on 'Restart Server' button

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
Latest released: [roop unleashed 4.0.0](https://github.com/C0untFloyd/roop-unleashed) python: 3.10.14 • torch: 2.1.2+cu118 • gradio: 4.32.1

**Screenshots**

![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/2f862093-9cc7-4611-953b-89780c3ab3dd)

**Comment by mammuthus** [comment]
It was resolved only by a full restart of roop.

I was able to reproduce the issue more clearly:

1. Loaded the input face resource: man.jpg
2. Loaded the target face resource: man2.jpg
3. Made a generation
4. Pressed 'Clean temp folder'
5. roop is now broken

**Before cleaning:**

![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/7825daa7-af5c-41a6-b380-7586d2dd368f)

**After cleaning:** 

![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/f02598e5-9fec-4814-a19a-35ec2476295f)

**So:**

- The 'Clean temp folder' button doesn't clean the temp folder; it just removes it.
- The 'Server Restart' button recreates the temp folder  (obviously, it's empty), but for some reasons, roop continue to refer to the old generation sources.

**Questions:**

- Why does the 'Clean temp folder' button remove the temp folder instead of cleaning it?
- Why does roop continue to refer to the old generation sources after cleaning?

**Comment by C0untFloyd** [comment]
> Why does the 'Clean temp folder' button remove the temp folder instead of cleaning it?

Because it's a lot faster and easier than to walk through all subfolders and files individually

> Why does roop continue to refer to the old generation sources after cleaning?

Because your browser and the browser framework I'm using still locks some files and I have no way of knowing this. Best is to just do a complete restart like you did or do this before any processing happened.

**Comment by CassySpencer** [comment]
Even after ITV complete restart, reboot and manual deleting of a whole bunch of Te folders and the original source files as well as the newly generated files, all of my historical files are still in the generated list. And then when I click on the link it shows the file.

Where are these files actually stored on a Mac?
