### ISSUE TITLE
ModuleNotFoundError: No module named 'onnxruntime'

### ISSUE THREAD

**Issue by khenny158** [C0untFloyd/roop-unleashed#833]
Traceback (most recent call last):
  File "C:\Users\User\Downloads\roop-cam\roop-cam\run.py", line 3, in <module>
    from roop import core
  File "C:\Users\User\Downloads\roop-cam\roop-cam\roop\core.py", line 17, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'
Press any key to continue . . .

I have no knowledge of programming or coding but i tried running the cpu version of the roop cam and this is the error i keep getting

**Comment by C0untFloyd** [comment]
Wrong repo?
