### ISSUE TITLE
[WinError 2] The specific file is not found

### ISSUE THREAD

**Issue by Senooy** [C0untFloyd/roop-unleashed#92]
**Describe the bug**

When I process to start the face swap, this error happens. Just updated to gradio, everything was fine before that

[ROOP.CORE] Processing video E:\IA\deepfake\roop-unleashed\installer\roop-unleashed\temp\0dc82691e94df19c35910464b035fdc9a73c8f74\1691877048783096.webm
Traceback (most recent call last):
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "E:\IA\deepfake\roop-unleashed\installer\roop-unleashed\roop\ui.py", line 599, in start_swap
    batch_process([file.name for file in target_files], use_clip, clip_text)
  File "E:\IA\deepfake\roop-unleashed\installer\roop-unleashed\roop\core.py", line 291, in batch_process
    fps = util.detect_fps(v)
  File "E:\IA\deepfake\roop-unleashed\installer\roop-unleashed\roop\utilities.py", line 43, in detect_fps
    output = subprocess.check_output(command).decode().strip().split('/')
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\IA\deepfake\roop-unleashed\installer\installer_files\env\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

**To Reproduce**
2. Click on 'Start button'

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you try to use a GPU?
- [x] No. I am not using the `---gpu` flag (Where to we add this ?)
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Screenshots**

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by primeinc** [comment]
According to the traceback, the error seems to be occurring within a function that's attempting to detect frames per second (FPS) from a video file, possibly by running an external command using the subprocess module.

I'm guessing it can't find ffprobe.exe

open a command prompt or powershell and type `ffprobe -version` and paste the results here. 

If you see `ffprobe: The term 'ffprobe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.` Then something is wrong with your path or ffmpeg install. 

Good luck!

**Comment by C0untFloyd** [comment]
Looks like ffmpeg is missing, perhaps download was interrupted while installing? You could try installing it yourself (with adding it to PATH).

**Comment by chandu375** [comment]
hey is you fixed, how?
