### ISSUE TITLE
File Not Found error

### ISSUE THREAD

**Issue by AdrianTheFrog** [C0untFloyd/roop-unleashed#95]
I am able to use the program on images and in the live cam, and I am able to preview individual frames of the video at the bottom, with the face swap setting on. However, I get this error when pressing the start button with a video:
```
[ROOP.CORE] Processing video C:\Users\afsw7\roop-unleashed\temp\e71c389e5f4bef81d63405ae2b6eaec90ff2ab8e\WIN_20230813_22_28_36_Pro.mp4
Traceback (most recent call last):
  File "C:\Users\afsw7\roop-unleashed\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\afsw7\roop-unleashed\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\afsw7\roop-unleashed\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\afsw7\roop-unleashed\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\afsw7\roop-unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\afsw7\roop-unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\afsw7\roop-unleashed\lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\afsw7\roop-unleashed\roop\ui.py", line 603, in start_swap
    batch_process([file.name for file in target_files], use_clip, clip_text)
  File "C:\Users\afsw7\roop-unleashed\roop\core.py", line 300, in batch_process
    fps = util.detect_fps(v)
  File "C:\Users\afsw7\roop-unleashed\roop\utilities.py", line 43, in detect_fps
    output = subprocess.check_output(command).decode().strip().split('/')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Roop is installed with git on windows, on an NVIDIA GPU.

**Comment by C0untFloyd** [comment]
Your missing ffmpeg installation or it's not added to PATH.
