### ISSUE TITLE
error "onnx.ModelProto"and ffmpeg not found

### ISSUE THREAD

**Issue by darmikota** [C0untFloyd/roop-unleashed#993]
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\user\Desktop\roop-unleashed-main\installer\roop-unleashed\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'has_user_compute_stream': '0', 'cudnn_conv1d_pad_to_nc1d': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'enable_cuda_graph': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'tunable_op_max_tuning_duration_ms': '0', 'enable_skip_layer_norm_strict_mode': '0', 'prefer_nhwc': '0', 'use_ep_level_unified_stream': '0'}, 'CPUExecutionProvider': {}}
find model: C:\Users\user\Desktop\roop-unleashed-main\installer\roop-unleashed\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Traceback (most recent call last):
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\queueing.py", line 575, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\gradio\utils.py", line 809, in gen_wrapper
    response = next(iterator)
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\roop-unleashed\ui\tabs\faceswap_tab.py", line 728, in start_swap
    batch_process_regular(output_method, list_files_process, mask_engine, clip_text, processing_method == "In-Memory processing", imagemask, restore_original_mouth, num_swap_steps, progress, SELECTED_INPUT_FACE_INDEX)
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\roop-unleashed\roop\core.py", line 236, in batch_process_regular
    process_mgr.initialize(roop.globals.INPUT_FACESETS, roop.globals.TARGET_FACES, options)
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\roop-unleashed\roop\ProcessMgr.py", line 136, in initialize
    p.Initialize(extoption)
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\roop-unleashed\roop\processors\FaceSwapInsightFace.py", line 28, in Initialize
    graph = onnx.load(model_path).graph
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\onnx\__init__.py", line 210, in load_model
    model = _get_serializer(format, f).deserialize_proto(_load_bytes(f), ModelProto())
  File "C:\Users\user\Desktop\roop-unleashed-main\installer\installer_files\env\lib\site-packages\onnx\serialization.py", line 118, in deserialize_proto
    decoded = typing.cast(Optional[int], proto.ParseFromString(serialized))
google.protobuf.message.DecodeError: Error parsing message with type 'onnx.ModelProto'
Aborting processing - please wait for the remaining threads to be stopped

**Comment by FreshStudent** [comment]
google.protobuf.message.DecodeError: Error parsing message with type 'onnx.ModelProto'
